/* JS */ gapi.loaded_0(function(_){var window=this;
_.l=function(a){throw a;};_.n=void 0;_.p=!0;_.r=null;_.t=!1;_.aa=function(){return function(a){return a}};_.u=function(){return function(){}};_.ba=function(a){return function(c){this[a]=c}};_.x=function(a){return function(){return this[a]}};_.y=function(a){return function(){return a}};_.B=function(a,c,f){a=a.split(".");f=f||_.C;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&(0,_.E)(c)?f[g]=c:f=f[g]?f[g]:f[g]={}};
_.ca=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof window.Array)return"array";if(a instanceof window.Object)return c;var f=window.Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.E=function(a){return a!==_.n};_.ea=function(a){return"array"==(0,_.ca)(a)};_.fa=function(a){var c=(0,_.ca)(a);return"array"==c||"object"==c&&"number"==typeof a.length};_.F=function(a){return"string"==typeof a};_.ga=function(a){return"function"==(0,_.ca)(a)};_.ha=function(a){var c=typeof a;return"object"==c&&a!=_.r||"function"==c};_.ia=function(a){return a[_.ja]||(a[_.ja]=++_.ka)};
_.la=function(a,c,f){return a.call.apply(a.bind,arguments)};_.ma=function(a,c,f){a||(0,_.l)((0,window.Error)());if(2<arguments.length){var g=window.Array.prototype.slice.call(arguments,2);return function(){var f=window.Array.prototype.slice.call(arguments);window.Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};
_.H=function(a,c,f){_.H=window.Function.prototype.bind&&-1!=window.Function.prototype.bind.toString().indexOf("native code")?_.la:_.ma;return _.H.apply(_.r,arguments)};_.na=function(a,c){var f=window.Array.prototype.slice.call(arguments,1);return function(){var c=window.Array.prototype.slice.call(arguments);c.unshift.apply(c,f);return a.apply(this,c)}};_.K=function(a,c){function f(){}f.prototype=c.prototype;a.B=c.prototype;a.prototype=new f;a.prototype.constructor=a};_._DumpException=function(a){(0,_.l)(a)};
_.oa=_.oa||{};_.C=this;_.ja="closure_uid_"+(1E9*window.Math.random()>>>0);_.ka=0;_.qa=window.Date.now||function(){return+new window.Date};window.Function.prototype.bind=window.Function.prototype.bind||function(a,c){if(1<arguments.length){var f=window.Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.H.apply(_.r,f)}return(0,_.H)(this,a)};
_.ra=window.gapi||{};_.sa=window.gadgets||{};_.L=window.osapi=window.osapi||{};_.google=window.google||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:_.t},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.t},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.t},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://plusone.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator"},appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"chili.people.list":_.p,"pos.plusones.list":_.p,"pos.plusones.get":_.p,"chili.people.get":_.p,
"pos.plusones.insert":_.p,"chili.activities.list":_.p,"pos.plusones.delete":_.p,"chili.activities.get":_.p,"chili.activities.search":_.p,"pos.plusones.getSignupState":_.p},requestCache:{enabled:_.p},versions:{chili:"v1",pos:"v1"},rpc:"/rpc",root:"https://www.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:_.p},transport:{isProxyShared:_.p},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:_.t}},drive_saver:{driveUrl:"https://drive.google.com"}});

_.va=function(a,c,f){return a[c]=a[c]||f};_.N=function(){var a;if((a=window.Object.create)&&_.wa.test(a))a=a(_.r);else{a={};for(var c in a)a[c]=_.n}return a};_.xa=function(a,c,f){var g=(0,window.RegExp)("([#].*&|[#])"+c+"=([^&#]*)","g");c=(0,window.RegExp)("([?#].*&|[?#])"+c+"=([^&#]*)","g");if(a=a&&(g.exec(a)||c.exec(a)))try{f=(0,window.decodeURIComponent)(a[2])}catch(h){}return f};
_.ya=function(a,c){var f="";2E3<c.length&&(f=c.substring(2E3),c=c.substring(0,2E3));var g=a.createElement("div"),h=a.createElement("a");h.href=c;g.appendChild(h);g.innerHTML=g.innerHTML;c=(0,window.String)(g.firstChild.href);g.parentNode&&g.parentNode.removeChild(g);return c+f};_.za=function(){return(0,_.va)(_.Aa,"WI",(0,_.N)())};_.Ba=function(){return _.Aa.ucs};_.Ca=function(){return _.Aa.ssfn};_.Da=function(a){var c=window.___jsl=window.___jsl||{};c[a]=c[a]||[];return c[a]};
_.Ea=function(a){var c=window.___jsl=window.___jsl||{};c.cfg=!a&&c.cfg||{};return c.cfg};_.Fa=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};_.Ga=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!(0,_.Fa)(a[f])&&!(0,_.Fa)(c[f])?(0,_.Ga)(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=(0,_.Fa)(c[f])?[]:{},(0,_.Ga)(a[f],c[f])):a[f]=c[f])};
_.Ha=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var c;try{c=window.JSON.parse(a)}catch(f){}if("object"===typeof c)return c;try{c=(new window.Function("return ("+a+"\n)"))()}catch(g){}if("object"===typeof c)return c;try{c=(new window.Function("return ({"+a+"\n})"))()}catch(h){}return"object"===typeof c?c:{}}};
_.Ia=function(a){(0,_.Ea)(_.p);var c=window.___gcfg,f=(0,_.Da)("cu");if(c&&c!==window.___gu){var g={};(0,_.Ga)(g,c);f.push(g);window.___gu=c}var c=(0,_.Da)("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],k=[];k.push.apply(k,(0,_.Da)("us"));for(var m=0;m<h.length;++m)for(var q=h[m],s=0;s<k.length;++s)q.src&&0==q.src.indexOf(k[s])&&g.push(q);0==g.length&&(0<h.length&&h[h.length-1].src)&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)g[h].getAttribute("gapi_processed")||
(g[h].setAttribute("gapi_processed",_.p),(k=g[h])?(m=k.nodeType,k=3==m||4==m?k.nodeValue:k.textContent||k.innerText||k.innerHTML||""):k=_.n,(k=(0,_.Ha)(k))&&c.push(k));a&&(g={},(0,_.Ga)(g,a),f.push(g));g=(0,_.Da)("cd");a=0;for(c=g.length;a<c;++a)(0,_.Ga)((0,_.Ea)(),g[a]);g=(0,_.Da)("ci");a=0;for(c=g.length;a<c;++a)(0,_.Ga)((0,_.Ea)(),g[a]);a=0;for(c=f.length;a<c;++a)(0,_.Ga)((0,_.Ea)(),f[a])};
_.O=function(a,c){if(!a)return(0,_.Ea)();for(var f=a.split("/"),g=(0,_.Ea)(),h=0,k=f.length;g&&"object"===typeof g&&h<k;++h)g=g[f[h]];return h===f.length&&g!==_.n?g:c};_.Ja=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),k=0,m=h.length;k<m-1;++k)var q={},g=g[h[k]]=q;g[h[k]]=c}(0,_.Ia)(f)};_.Ka=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),(0,_.va)(_.Aa,"ci",[]).push(a),window.__GOOGLEAPIS=_.n)}; _.P=function(a,c){c="function"==typeof _.La&&(0,_.La)(a,c)||c;(0,_.B)(a,c,_.n)};
_.Q=window;_.Ma=window.document;_.Na=_.Q.location;_.wa=/\[native code\]/;_.Oa=(0,_.va)(_.Q,"gapi",{});_.Aa=(0,_.va)(_.Q,"___jsl",(0,_.N)());(0,_.va)(_.Aa,"I",0);(0,_.va)(_.Aa,"hel",10);_.Ka&&(0,_.Ka)();(0,_.Ia)();(0,_.P)("gapi.config.get",_.O);(0,_.P)("gapi.config.update",_.Ja);

_.Ua=function(a,c){return window.Object.prototype.hasOwnProperty.call(a,c)};_.Va=function(a,c){a=a||{};for(var f in a)(0,_.Ua)(a,f)&&(c[f]=a[f])};_.Wa=function(a,c,f,g,h){if(a[g+"EventListener"])a[g+"EventListener"](c,f,_.t);else if(a[h+"tachEvent"])a[h+"tachEvent"]("on"+c,f)};_.Xa=function(a,c,f){(0,_.Wa)(a,c,f,"add","at")};

_.ul=window.googleapis&&window.googleapis.server||{};
if(window.JSON&&window.JSON.parse&&window.JSON.stringify)_.Zb=function(){function a(a){return this[a]}var c=/___$/;return{parse:function(a){try{return window.JSON.parse(a)}catch(c){return _.t}},stringify:function(f){function g(c){return h.call(this,c,a)}var h=window.JSON.stringify,k=window.Array.prototype.toJSON&&'"[{\\"x\\": 1}]"'===h([{x:1}])?g:h;try{return k(f,function(a,f){return!c.test(a)?f:_.n})}catch(m){return _.r}}}}();
if(!window.JSON||!window.JSON.parse||!window.JSON.stringify)_.Zb=function(){function a(a){return 10>a?"0"+a:a}function c(a){var h,k,m;h=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof a){case "string":return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];if(c)return c;c=a.charCodeAt();return"\\u00"+window.Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?(0,window.String)(a):"null";case "boolean":case "null":return(0,window.String)(a);case "object":if(!a)return"null";
h=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){m=a.length;for(k=0;k<m;k+=1)h.push(c(a[k])||"null");return"["+h.join(",")+"]"}for(k in a)!/___$/.test(k)&&a.hasOwnProperty(k)&&"string"===typeof k&&(m=c(a[k]))&&h.push(c(k)+":"+m);return"{"+h.join(",")+"}"}return""}window.Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",a(this.getUTCMonth()+1),"-",a(this.getUTCDate()),"T",a(this.getUTCHours()),":",a(this.getUTCMinutes()),":",a(this.getUTCSeconds()),"Z"].join("")};
var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:c,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+a+")"):_.t}}}();
_.Zb.$k=function(a){var c={};if(a===_.r||a===_.n)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];_.r===g||_.n===g||(c[f]="string"===typeof g?g:_.Zb.stringify(g))}return c};(0,_.P)("gadgets.json.flatten",_.Zb.$k);(0,_.P)("gadgets.json.parse",_.Zb.parse);(0,_.P)("gadgets.json.stringify",_.Zb.stringify);(0,_.P)("gadgets.json.flatten",_.Zb.$k);(0,_.P)("gadgets.json.parse",_.Zb.parse);(0,_.P)("gadgets.json.stringify",_.Zb.stringify);


_.R=_.R||{};
_.R=_.R||{};
(function(){function a(a,c){return window.String.fromCharCode(c)}var c={0:_.t,10:_.p,13:_.p,34:_.p,39:_.p,60:_.p,62:_.p,92:_.p,8232:_.p,8233:_.p,65282:_.p,65287:_.p,65308:_.p,65310:_.p,65340:_.p};_.R.escape=function(a,c){if(a){if("string"===typeof a)return _.R.eg(a);if("array"===typeof a)for(var h=0,k=a.length;h<k;++h)a[h]=_.R.escape(a[h]);else if("object"===typeof a&&c){h={};for(k in a)a.hasOwnProperty(k)&&(h[_.R.eg(k)]=_.R.escape(a[k],_.p));return h}}return a};_.R.eg=function(a){if(!a)return a;for(var g= [],h,k,m=0,q=a.length;m<q;++m)h=a.charCodeAt(m),k=c[h],k===_.p?g.push("&#",h,";"):k!==_.t&&g.push(a.charAt(m));return g.join("")};_.R.Qy=function(c){return!c?c:c.replace(/&#([0-9]+);/g,a)}})();

_.R=_.R||{};
(function(){function a(c){var f="";if(3==c.nodeType||4==c.nodeType)f=c.nodeValue;else if(c.innerText)f=c.innerText;else if(c.innerHTML)f=c.innerHTML;else if(c.firstChild){f=[];for(c=c.firstChild;c;c=c.nextSibling)f.push(a(c));f=f.join("")}return f}_.R.createElement=function(a){var f;if(!window.document.body||window.document.body.namespaceURI)try{f=window.document.createElementNS("http://www.w3.org/1999/xhtml",a)}catch(g){}return f||window.document.createElement(a)};_.R.ai=function(a){var f=_.R.createElement("iframe");
try{var g=["<","iframe"],h=a||{},k;for(k in h)h.hasOwnProperty(k)&&(g.push(" "),g.push(k),g.push('="'),g.push(_.R.eg(h[k])),g.push('"'));g.push("></");g.push("iframe");g.push(">");var m=_.R.createElement(g.join(""));if(m&&(!f||m.tagName==f.tagName&&m.namespaceURI==f.namespaceURI))f=m}catch(q){}g=f;a=a||{};for(var s in a)a.hasOwnProperty(s)&&(g[s]=a[s]);return f};_.R.jl=function(){if(window.document.body)return window.document.body;try{var a=window.document.getElementsByTagNameNS("http://www.w3.org/1999/xhtml", "body");if(a&&1==a.length)return a[0]}catch(f){}return window.document.documentElement||window.document};_.R.ky=function(c){return a(c)}})();

_.ac=function(){function a(a){c(1,a)}function c(a,c){if(!(a<f)&&g)if(2===a&&g.warn)g.warn(c);else if(3===a&&g.error)try{g.error(c)}catch(m){}else g.log&&g.log(c)}_.ta=function(a){c(2,a)};_.ua=function(a){c(3,a)};_.$b=(0,_.u)();a.INFO=1;a.WARNING=2;a.NONE=4;var f=1,g=window.console?window.console:window.opera?window.opera.postError:_.n;return a}();

_.R=_.R||{};(function(){var a=[];_.R.Ay=function(c){a.push(c)};_.R.Hy=function(){for(var c=0,f=a.length;c<f;++c)a[c]()}})();
_.R=_.R||{};
(function(){var a=_.r;_.R.la=function(c){var f="undefined"===typeof c;if(a!==_.r&&f)return a;var g={};c=c||window.location.href;var h=c.indexOf("?"),k=c.indexOf("#");c=(-1===k?c.substr(h+1):[c.substr(h+1,k-h-1),"&",c.substr(k+1)].join("")).split("&");for(var h=window.decodeURIComponent?window.decodeURIComponent:window.unescape,k=0,m=c.length;k<m;++k){var q=c[k].indexOf("=");if(-1!==q){var s=c[k].substring(0,q),q=c[k].substring(q+1),q=q.replace(/\+/g," ");try{g[s]=h(q)}catch(v){}}}f&&(a=g);return g}; _.R.la()})();
(0,_.P)("gadgets.util.getUrlParameters",_.R.la);
_.ec=function(a){_.fc&&_.fc.log&&_.fc.log(a)};_.gc=function(){};_.fc=window.console;
_.hc=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&(0,_.Ja)(a());return{I:function(a,f,g){g&&g((0,_.O)())},get:function(a){return(0,_.O)(a)},update:function(a,f){f&&(0,_.l)("Config replacement is not supported");(0,_.Ja)(a)},Y:(0,_.u)()}}();
(0,_.P)("gadgets.config.register",_.hc.I);(0,_.P)("gadgets.config.get",_.hc.get);(0,_.P)("gadgets.config.init",_.hc.Y);(0,_.P)("gadgets.config.update",_.hc.update);
_.ic=_.ic||{};_.ic.xn=_.r;_.ic.Hm=_.r;_.ic.Hg=_.r;_.ic.frameElement=_.r;_.ic=_.ic||{};
_.ic.jk||(_.ic.jk=function(){function a(a,c,f){"undefined"!=typeof window.addEventListener?window.addEventListener(a,c,f):"undefined"!=typeof window.attachEvent&&window.attachEvent("on"+a,c);"message"===a&&(window.___jsl=window.___jsl||{},a=window.___jsl,a.RPMQ=a.RPMQ||[],a.RPMQ.push(c))}function c(a){var c=_.Zb.parse(a.data);if(c&&c.f){(0,_.$b)("gadgets.rpc.receive("+window.name+"): "+a.data);var g=_.S.pe(c.f);h&&("undefined"!==typeof a.origin?a.origin!==g:a.domain!==/^.+:\/\/([^:]+).*/.exec(g)[1])?(0,_.ua)("Invalid rpc message origin. "+
g+" vs "+(a.origin||"")):f(c,a.origin)}}var f,g,h=_.p;return{kl:(0,_.y)("wpm"),b:(0,_.y)(_.p),Y:function(k,m){_.hc.I("rpc",_.r,function(a){if("true"===(0,window.String)((a&&a.rpc||{}).disableForceSecure))h=_.t});f=k;g=m;a("message",c,_.t);g("..",_.p);return _.p},Ff:function(a){g(a,_.p);return _.p},call:function(a,c,f){var g=_.S.pe(a),h=_.S.Ek(a);g?window.setTimeout(function(){var a=_.Zb.stringify(f);(0,_.$b)("gadgets.rpc.send("+window.name+"): "+a);h.postMessage(a,g)},0):".."!=a&&(0,_.ua)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return _.p}}}());
_.ic=_.ic||{};
_.ic.kg||(_.ic.kg=function(){function a(a,c){function f(){a.apply({},arguments)}jb[c]=jb[c]||f;return kb+"."+c}function c(){if(M===_.r&&window.document.body&&v){var a=v+"?cb="+window.Math.random()+"&origin="+Pb+"&jsl=1",f=window.document.createElement("div");f.style.height="1px";f.style.width="1px";a='<object height="1" width="1" id="'+s+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(f);f.innerHTML=a;M=f.firstChild}++J;G!==_.r&&(M!==_.r||50<=J)?window.clearTimeout(G):G=window.setTimeout(c,100)}function f(){da[".."]||(q(".."),V++,50<=V&&pa!==_.r?(window.clearTimeout(pa),pa=_.r):pa=window.setTimeout(f,100))}function g(){if(M!==_.r&&M.setup)for(;0<I.length;){var a=I.shift(),c=a.uu;M.setup(a.Me,".."===c?_.S.Ih:c,".."===c?"INNER":"OUTER")}G!==_.r&&window.clearTimeout(G);G=_.r}function h(){!da[".."]&&pa===_.r&&
(pa=window.setTimeout(f,100))}function k(a,c,f){c=_.S.pe(a);var g=_.S.je(a);M["sendMessage_"+(".."===a?_.S.Ih:a)+"_"+g+"_"+(".."===a?"INNER":"OUTER")].call(M,_.Zb.stringify(f),c);return _.p}function m(a,c){var f=_.Zb.parse(a),g=f._scr;g?(D(g,_.p),da[g]=_.p,".."!==g&&q(g,_.p)):window.setTimeout(function(){z(f,c)},0)}function q(a,c){var f=_.S.Ih,g={};g._scr=c?"..":f;g._pnt=f;k(a,f,g)}var s="___xpcswf",v=_.r,w=_.t,z=_.r,D=_.r,M=_.r,I=[],G=_.r,J=0,V=0,pa=_.r,da={},Pb=window.location.protocol+"//"+window.location.host,
kb,jb=function(){window.___jsl=window.___jsl||{};var a=window.___jsl._fm={};kb="___jsl._fm";return a}();_.hc.I("rpc",_.r,function(a){w&&(v=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(g,"ready");a(h,"setupDone");a(m,"receiveMessage");return{kl:(0,_.y)("flash"),b:(0,_.y)(_.p),Y:function(a,c){z=a;D=c;return w=_.p},Ff:function(a,f){I.push({Me:f,uu:a});M===_.r&&G===_.r&&(G=window.setTimeout(c,100));return _.p},call:k,Rp:m,d:g,i:h}}());
if(!window.gadgets||!window.gadgets.rpc){_.S=function(){function a(){}function c(a,c){if(!ib[a]){var f=lc;c||(f=Ie);ib[a]=f;for(var g=dg[a]||[],h=0;h<g.length;++h){var k=g[h];k.t=da[a];f.call(a,k.f,k)}dg[a]=[]}}function f(){function a(){Op=_.p}Pp||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,_.t):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),Pp=_.p)}function g(c,g,h,k,m){if(!da[g]||da[g]!==h)(0,_.ua)("Invalid gadgets.rpc token. "+da[g]+
" vs "+h),a(g,2);m.onunload=function(){jb[g]&&!Op&&(a(g,1),_.S.Hj(g))};f();k=_.Zb.parse((0,window.decodeURIComponent)(k))}function h(f,g){if(f&&"string"===typeof f.s&&"string"===typeof f.f&&f.a instanceof window.Array)if(da[f.f]&&da[f.f]!==f.t&&((0,_.ua)("Invalid gadgets.rpc token. "+da[f.f]+" vs "+f.t),a(f.f,2)),"__ack"===f.s)window.setTimeout(function(){c(f.f,_.p)},0);else{f.c&&(f.callback=function(a){_.S.call(f.f,(f.g?"legacy__":"")+"__cb",_.r,f.c,a)});if(g){var h=k(g);f.origin=g;var m=f.r;if(!m||
k(m)!=h)m=g;f.referer=m}h=(J[f.s]||J[""]).apply(f,f.a);f.c&&"undefined"!==typeof h&&_.S.call(f.f,"__cb",_.r,f.c,h)}}function k(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));var f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1),c=c.substring(0,g);if("http"===
a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f}function m(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):_.r}}return _.r}function q(a){if("undefined"===typeof a||".."===a)return window.parent;var c=m(a);if(c)return window.top.frames[c.id];a=(0,window.String)(a);return(c=window.frames[a])?c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:_.r}function s(a,c){if(jb[a]!==_.p){"undefined"===typeof jb[a]&&
(jb[a]=0);var f=q(a);(".."===a||f!=_.r)&&lc.Ff(a,c)===_.p?jb[a]=_.p:jb[a]!==_.p&&10>jb[a]++?window.setTimeout(function(){s(a,c)},500):(ib[a]=Ie,jb[a]=_.p)}}function v(a){(a=V[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function w(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+
c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));V[a]=c;"undefined"!==typeof f&&(pa[a]=!!f)}function z(a,c){c=c||"";da[a]=(0,window.String)(c);s(a,c)}function D(a){a=(a.passReferrer||"").split(":",2);Zh=a[0]||"none";al=a[1]||"origin"}function M(a){"true"===(0,window.String)(a.useLegacyProtocol)&&(lc=_.ic.Hg||Ie,lc.Y(h,c))}function I(a,c){function f(g){g=g&&g.rpc||{};D(g);var h=g.parentRelayUrl||"",h=k(bb.parent||c)+h;w("..",h,"true"===(0,window.String)(g.useLegacyProtocol));M(g);z("..",
a)}!bb.parent&&c?f({}):_.hc.I("rpc",_.r,f)}function G(a,c,f){if(".."===a)I(f||bb.rpctoken||bb.ifpctok||"",c);else a:{var g=_.r;if("/"!=a.charAt(0)){if(!_.R)break a;(g=window.document.getElementById(a))||(0,_.l)((0,window.Error)("i`"+a))}g=g&&g.src;c=c||_.S.ja(g);w(a,c);c=_.R.la(g);z(a,f||c.rpctoken)}}var J={},V={},pa={},da={},Pb=0,kb={},jb={},bb={},ib={},dg={},Zh=_.r,al=_.r,Xy=window.top!==window.self,bl=window.name,cl=window.console,Qp=cl&&cl.log&&function(a){cl.log(a)}||(0,_.u)(),Ie=function(){function a(c){return function(){Qp(c+
": call ignored")}}return{getCode:(0,_.y)("noop"),isParentVerifiable:(0,_.y)(_.p),init:a("init"),setup:a("setup"),call:a("call")}}();_.R&&(bb=_.R.la());var Op=_.t,Pp=_.t,lc=function(){if("flash"==bb.rpctx)return _.ic.kg;if("rmr"==bb.rpctx)return _.ic.xn;var a="function"===typeof window.postMessage?_.ic.jk:"object"===typeof window.postMessage?_.ic.jk:window.ActiveXObject?_.ic.kg?_.ic.kg:_.ic.Hm?_.ic.Hm:_.ic.Hg:0<window.navigator.userAgent.indexOf("WebKit")?_.ic.xn:"Gecko"===window.navigator.product?
_.ic.frameElement:_.ic.Hg;a||(a=Ie);return a}();J[""]=function(){Qp("Unknown RPC service: "+this.s)};J.__cb=function(a,c){var f=kb[a];f&&(delete kb[a],f.call(this,c))};return{xa:function(c){"function"===typeof c.Cn&&(a=c.Cn)},I:function(a,c){("__cb"===a||"__ack"===a)&&(0,_.l)((0,window.Error)("j"));""===a&&(0,_.l)((0,window.Error)("k"));J[a]=c},Xd:function(a){("__cb"===a||"__ack"===a)&&(0,_.l)((0,window.Error)("l"));""===a&&(0,_.l)((0,window.Error)("m"));delete J[a]},mn:function(a){J[""]=a},ho:function(){delete J[""]},
dl:(0,_.u)(),call:function(a,c,f,g){a=a||"..";var h="..";".."===a?h=bl:"/"==a.charAt(0)&&(h=_.S.ja(window.location.href),h="/"+bl+(h?"|"+h:""));++Pb;f&&(kb[Pb]=f);var k={s:c,f:h,c:f?Pb:0,a:window.Array.prototype.slice.call(arguments,3),t:da[a],l:!!pa[a]},q;a:if("bidir"===Zh||"c2p"===Zh&&".."===a||"p2c"===Zh&&".."!==a){q=window.location.href;var s="?";if("query"===al)s="#";else if("hash"===al)break a;s=q.lastIndexOf(s);s=-1===s?q.length:s;q=q.substring(0,s)}else q=_.r;q&&(k.r=q);".."!==a&&m(a)==_.r&&
!window.document.getElementById(a)||(q=ib[a],!q&&m(a)!==_.r&&(q=lc),0===c.indexOf("legacy__")&&(q=lc,k.s=c.substring(8),k.c=k.c?k.c:Pb),k.g=_.p,k.r=h,q?(pa[a]&&(q=_.ic.Hg),q.call(a,h,k)===_.t&&(ib[a]=Ie,lc.call(a,h,k))):dg[a]?dg[a].push(k):dg[a]=[k])},gf:v,Ac:w,kh:z,Gf:G,je:function(a){return da[a]},Hj:function(a){delete V[a];delete pa[a];delete da[a];delete jb[a];delete ib[a]},sl:function(){return lc.kl()},jn:function(a,c){4<a.length?lc.Rp(a,h):g.apply(_.r,a.concat(c))},ln:function(a){a.a=window.Array.prototype.slice.call(a.a);
window.setTimeout(function(){h(a)},0)},ja:k,pe:function(a){var c=_.r,c=v(a);c||(c=(c=m(a))?c.origin:".."==a?bb.parent:window.document.getElementById(a).src);return k(c)},Y:function(){lc.Y(h,c)===_.t&&(lc=Ie);Xy?G(".."):_.hc.I("rpc",_.r,function(a){a=a.rpc||{};D(a);M(a)})},Ek:q,Qp:m,b:"__ack",Ih:bl||"..",j:0,i:1,d:2}}();_.S.Y()}else if("undefined"==typeof _.S||!_.S)_.S=window.gadgets.rpc,_.S.xa=_.S.config,_.S.I=_.S.register,_.S.Xd=_.S.unregister,_.S.mn=_.S.registerDefault,_.S.ho=_.S.unregisterDefault,
_.S.dl=_.S.forceParentVerifiable,_.S.call=_.S.call,_.S.gf=_.S.getRelayUrl,_.S.Ac=_.S.setRelayUrl,_.S.kh=_.S.setAuthToken,_.S.Gf=_.S.setupReceiver,_.S.je=_.S.getAuthToken,_.S.Hj=_.S.removeReceiver,_.S.sl=_.S.getRelayChannel,_.S.jn=_.S.receive,_.S.ln=_.S.receiveSameDomain,_.S.ja=_.S.getOrigin,_.S.pe=_.S.getTargetOrigin,_.S.Ek=_.S._getTargetWin,_.S.Qp=_.S._parseSiblingId;
_.S.xa({Cn:function(a){(0,_.l)((0,window.Error)("n`"+a))}});_.$b=_.gc;(0,_.P)("gadgets.rpc.config",_.S.xa);(0,_.P)("gadgets.rpc.register",_.S.I);(0,_.P)("gadgets.rpc.unregister",_.S.Xd);(0,_.P)("gadgets.rpc.registerDefault",_.S.mn);(0,_.P)("gadgets.rpc.unregisterDefault",_.S.ho);(0,_.P)("gadgets.rpc.forceParentVerifiable",_.S.dl);(0,_.P)("gadgets.rpc.call",_.S.call);(0,_.P)("gadgets.rpc.getRelayUrl",_.S.gf);(0,_.P)("gadgets.rpc.setRelayUrl",_.S.Ac);(0,_.P)("gadgets.rpc.setAuthToken",_.S.kh);(0,_.P)("gadgets.rpc.setupReceiver",_.S.Gf);
(0,_.P)("gadgets.rpc.getAuthToken",_.S.je);(0,_.P)("gadgets.rpc.removeReceiver",_.S.Hj);(0,_.P)("gadgets.rpc.getRelayChannel",_.S.sl);(0,_.P)("gadgets.rpc.receive",_.S.jn);(0,_.P)("gadgets.rpc.receiveSameDomain",_.S.ln);(0,_.P)("gadgets.rpc.getOrigin",_.S.ja);(0,_.P)("gadgets.rpc.getTargetOrigin",_.S.pe);


_.jc=window.gapi&&window.gapi.util||{};
_.jc=_.jc||{};_.jc.Vh=function(){var a={lk:"bsh",sk:"h"};window.___jsl=window.___jsl||{};return{b:function(){return window.___jsl[a.lk]},ol:function(){return window.___jsl[a.sk]},Oj:function(c){window.___jsl[a.lk]=c},$t:function(c){window.___jsl[a.sk]=c}}}();

_.$a=function(a){var c=(0,_.O)("googleapis.config/sessionIndex");c==_.r&&(c=window.__X_GOOG_AUTHUSER);if(c==_.r){var f=window.google;f&&(c=f.authuser)}c==_.r&&(a==_.r&&(a=window.location.href),c=a?(0,_.xa)(a,"authuser")||_.r:_.r);return c==_.r?_.r:(0,window.String)(c)};
_.ab=function(a,c,f){a=(0,window.String)(a);if(((0,_.xa)(a,"authuser")||_.r)!=_.r||((0,_.xa)(a,"hd")||_.r)!=_.r)return a;c=(0,_.$a)(c);if(f){var g=a,h=g.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(h&&h[0]){var k=h[1],m=h[4],q=h[5];h[3]=="/"+f&&(g=(k||"")+(m||"/")+(q||""))}if((h=g.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&h[0])return k=h[2],a=h[4]||h[5],q=h[6],c!=_.r&&(g=(k||"")+"/"+f+"/"+(0,window.encodeURIComponent)(c)+(a||"/")+
(q||"")),g}f=c==_.r?(0,window.encodeURIComponent)("authuser")+"=0":c.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)((0,window.String)(c)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(c)].join(""):["authuser=",(0,window.encodeURIComponent)(c)].join("");a=a.split("#");c=a[0].indexOf("?");0>c?a[0]=[a[0],"?",f].join(""):(g=[a[0]],c<a[0].length-1&&g.push("&"),g.push(f),a[0]=g.join(""));return g=a.join("#")};

_.google.gn=_.ab;_.google.pr=function(a){return(0,_.$a)(a)};
_.Ok=function(a,c){this.b=a;var f=c||{};this.j=f.wy;this.d=f.domain;this.i=f.path;this.k=f.Lt};_.Pk=function(a){this.b=a};_.Qk=function(a){this.b=a;this.d=window.sessionStorage};_.Rk=/^[-+/_=.:|%&a-zA-Z0-9@]*$/;_.Sk=/^[A-Z_][A-Z0-9_]{0,63}$/;_.Ok.prototype.gh=function(){for(var a=this.b+"=",c=window.document.cookie.split(/;\s*/),f=0;f<c.length;++f){var g=c[f];if(0==g.indexOf(a))return g.substr(a.length)}};
_.Ok.prototype.write=function(a,c){_.Sk.test(this.b)||(0,_.l)("Invalid cookie name");_.Rk.test(a)||(0,_.l)("Invalid cookie value");var f=this.b+"="+a;this.d&&(f+=";domain="+this.d);this.i&&(f+=";path="+this.i);var g="number"===typeof c?c:this.j;if(0<=g){var h=new window.Date;h.setSeconds(h.getSeconds()+g);f+=";expires="+h.toUTCString()}this.k&&(f+=";secure");window.document.cookie=f};_.Ok.prototype.clear=function(){this.write("",0)}; _.Ok.iterate=function(a){for(var c=window.document.cookie.split(/;\s*/),f=0;f<c.length;++f)a(c[f].split("=")[0])};
_.Tk={};_.Pk.prototype.gh=function(){if(_.Tk.hasOwnProperty(this.b))return _.Tk[this.b]};_.Pk.prototype.write=function(a){_.Tk[this.b]=a};_.Pk.prototype.clear=function(){delete _.Tk[this.b]};_.Pk.iterate=function(a){for(var c in _.Tk)_.Tk.hasOwnProperty(c)&&a(c)};
_.Qk.prototype.gh=function(){return this.d.getItem(this.b)};_.Qk.prototype.write=function(a){this.d.setItem(this.b,a)};_.Qk.prototype.clear=function(){this.d.removeItem(this.b)};_.Qk.iterate=function(a){for(var c=0,f=window.sessionStorage.length;c<f;++c){var g=window.sessionStorage.key(c);a(g)}};

_.Uk=window.oauth2||{};_.Vk=window.auth_firstparty||{};
for(_.Wk=0;64>_.Wk;++_.Wk);
_.Xk=function(){return window.Math.floor((new window.Date).getTime()/1E3)};_.Yk=function(a){this.$m=a;this.oj=_.r};
_.Zk=function(a){if(!a)return _.r;"single_host_origin"!==a&&(a=_.S.ja(a));var c=window.location.hostname,f=c,g=_.$k;if("single_host_origin"!==a){f=a.split("://");if(2==f.length)g="https"===f.shift();else return(0,_.ec)("WARNING invalid cookie_policy: "+a),_.r;f=f[0]}if(-1!==f.indexOf(":"))f=c="";else{if(f!==c){a="."+f;if(c.lastIndexOf(a)!==c.length-a.length)return(0,_.ec)("Invalid cookie_policy domain: "+f),_.r;f=a}c=f.split(".").length-1}return{domain:f,Pd:g,gi:c}};
_.dl=function(a){if(!a)return _.r;var c=a.client_id;if(!c)return _.r;for(var c=c.toUpperCase(),f=0,g=_.el.length;f<g;++f){var h=c.split(_.el[f]);2==h.length&&""===h[1]&&(c=h[0])}c=c.replace(/-/g,"_").toUpperCase();40<c.length&&(f=(0,_.mc)(),f.update(c),c=f.Ye().toUpperCase());a=(0,_.Zk)(a.cookie_policy);return!a?_.r:!_.$k&&a.Pd?((0,_.ec)("WARNING: https cookie_policy set for http domain"),_.r):["GCSC",a.Pd?"E":"U","_",c,"_",a.Pd?"S":"H",a.gi].join("")};
_.fl=function(a){if(0!==a.indexOf("GCSC"))return _.r;var c={fj:_.t};a=a.substr(4);if(!a)return c;var f=a.charAt(0);a=a.substr(1);var g=a.lastIndexOf("_");if(-1==g)return c;var h=a.substr(g+1);a=a.substring(0,g);if("_"!==a.charAt(0))return c;a=a.substr(1);var k=h.substr(1),g="",m=window.location.hostname;if(""!==k){g=(0,window.parseInt)(k,10);if((0,window.isNaN)(g))return c;k=m.split(".");if(k.length<g-1)return c;k.length==g-1&&(m="."+m)}else m="";h=h.charAt(0);k="E"===f&&"S"===h;return!k&&("U"!==
f||"H"!==h)||k&&!_.$k?c:{fj:_.p,Pd:k,ey:a,domain:m,gi:g}};_.gl=function(a){return!a?_.r:{domain:a.domain,path:"/",Lt:a.Pd}};_.hl=function(a){var c=_.il[a];c||(c=new _.Yk(new _.Pk(a)),_.il[a]=c);return{Ke:c,key:a}};
_.jl=function(a,c){var f=c?_.kl:_.il,g=c?_.ll:_.ml,h=a&&(0,_.dl)(a),k=!!h;a&&!a.g_user_cookie_policy&&(g=_.Pk,h="token");if(!h)if(!c&&_.nl)h=_.nl;else return _.r;var m=f[h];if(!m){m=(0,_.fl)(h);if("token"!==h&&(!m||!m.fj))return _.r;m=new g(h,(0,_.gl)(m));c||(m=new _.Yk(m))}f[h]=m;return{Ke:m,key:h,Rq:k}};_.ol=function(a,c){var f=a&&"token"!==a?(0,_.hl)(a):(0,_.jl)();if(!f)return _.r;var g=f.Ke.gh();g&&(g.expires_at&&(0,_.Xk)()>g.expires_at)&&(f.Ke.clear(),g=_.r);g&&(g.error&&!c)&&(g=_.r);return g};
_.pl=function(a,c){var f="";if(!a)return f;var g=c||"&",h;for(h in a)if({}.hasOwnProperty.call(a,h)){var k;k=a[h];if(k!=_.r){var m=[(0,window.encodeURIComponent)(h),"="];if(k instanceof window.Array){for(var q=[],s=0;s<k.length;s++)q.push((0,window.encodeURIComponent)(k[s]));m.push(q.join("+"))}else m.push((0,window.encodeURIComponent)(k));k=m.join("")}else k="";k&&(f&&(f+=g),f+=k)}return f};_.ql=(0,_.O)("oauth-flow/persist")==_.p;_.ml=_.ql?_.Qk:_.Pk;_.$k="https:"===window.location.protocol;
_.rl=_.$k||"http:"===window.location.protocol?_.Ok:_.Pk;_.ll=_.ql?_.rl:_.Pk;_.il=(0,_.N)();_.kl=(0,_.N)();_.sl=(0,_.N)();_.nl=_.r;_.tl="state code cookie_policy g_user_cookie_policy authuser prompt g-oauth-window".split(" ");_.el=[".APPS.GOOGLEUSERCONTENT.COM","@DEVELOPER.GSERVICEACCOUNT.COM"];
_.Yk.prototype.write=function(a){var c=(0,_.N)(),f=(0,_.N)(),g;for(g in a)window.Object.prototype.hasOwnProperty.call(a,g)&&(f[g]=a[g],c[g]=a[g]);g=0;for(var h=_.tl.length;g<h;++g)delete f[_.tl[g]];a=(0,window.String)(a.authuser||0);g=(0,_.N)();g[a]=_.R.la("#"+(0,_.pl)(f));this.$m.write(_.Zb.stringify(g));this.oj=c};_.Yk.prototype.gh=(0,_.x)("oj");_.Yk.prototype.clear=function(){this.$m.clear();this.oj=(0,_.N)()};_.ml.iterate(function(a){var c=(0,_.fl)(a);c&&c.fj&&(_.il[a]=new _.Yk(new _.ml(a,(0,_.gl)(c))))}); _.ll.iterate(function(a){_.il[a]&&(_.kl[a]=new _.ll(a,(0,_.gl)((0,_.fl)(a))))});

_.jc.ja=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^\w*:\/\//.test(a)||(a=window.location.href);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));var f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};

_.vl=function(){var a=/\s*;\s*/;return{get:function(c,f){for(var g=c+"=",h=(window.document.cookie||"").split(a),k=0,m;m=h[k];++k)if(0==m.indexOf(g))return m.substr(g.length);return f}}}();
_.mc=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;w=v=0}function c(a){for(var c=m,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)c[f]=((c[f-3]^c[f-8]^c[f-14]^c[f-16])<<1|(c[f-3]^c[f-8]^c[f-14]^c[f-16])>>>31)&4294967295;a=h[0];for(var g=h[1],k=h[2],q=h[3],s=h[4],v,w,f=0;80>f;f++)40>f?20>f?(v=q^g&(k^q),w=1518500249):(v=g^k^q,w=1859775393):60>f?(v=g&k|q&(g|k),w=2400959708):(v=g^k^q,w=3395469782),v=((a<<5|a>>>27)&4294967295)+
v+s+w+c[f]&4294967295,s=q,q=k,k=(g<<30|g>>>2)&4294967295,g=a,a=v;h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+k&4294967295;h[3]=h[3]+q&4294967295;h[4]=h[4]+s&4294967295}function f(a,f){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var g=[],h=0,m=a.length;h<m;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==v)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64;for(;g<f;)if(k[v++]=a[g++],w++,64==v){v=0;for(c(k);g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64}}
function g(){var a=[],g=8*w;56>v?f(q,56-v):f(q,64-(v-56));for(var m=63;56<=m;m--)k[m]=g&255,g>>>=8;c(k);for(m=g=0;5>m;m++)for(var s=24;0<=s;s-=8)a[g++]=h[m]>>s&255;return a}for(var h=[],k=[],m=[],q=[128],s=1;64>s;++s)q[s]=0;var v,w;a();return{reset:a,update:f,Wk:g,Ye:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(window.Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};

_.Vk=function(){function a(){var a=window.__OVERRIDE_SID;a==_.r&&(a=_.vl.get("SID"));return!!a}return{cs:function(a){var f={SAPISIDHASH:_.p,APISIDHASH:_.p};return a&&(a.OriginToken||a.Authorization&&f[(0,window.String)(a.Authorization).split(" ")[0]])?_.p:_.t},vs:a,hr:function(){var c=_.r;a()&&(c=window.__PVT,c==_.r&&(c=_.vl.get("BEAT")));return c},af:function(){var c=_.jc.ja((0,window.String)(window.location.href));if(a()){var f=0==c.indexOf("https:")||0==c.indexOf("chrome-extension:"),g=f?"SAPISID": "APISID",h=f?window.__SAPISID:window.__APISID;h==_.r&&(h=_.vl.get(g));if(h)return f=f?"SAPISIDHASH":"APISIDHASH",g=(0,_.mc)(),g.reset(),g.update([h,c].join(" ")),f+" "+g.Ye().toLowerCase()}return _.r}}}();

_.R=_.R||{};_.R.Te=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):(0,_.ta)("cannot attachBrowserEvent: "+c)};_.R.tt=function(a,c,f,g){a.removeEventListener?a.removeEventListener(c,f,g):a.detachEvent?a.detachEvent("on"+c,f):(0,_.ta)("cannot removeBrowserEvent: "+c)};

_.nc=function(a){if("complete"===_.Ma.readyState)a();else{var c=_.t,f=function(){if(!c)return c=_.p,a.apply(this,arguments)};_.Q.addEventListener?(_.Q.addEventListener("load",f,_.t),_.Q.addEventListener("DOMContentLoaded",f,_.t)):_.Q.attachEvent&&(_.Q.attachEvent("onreadystatechange",function(){"complete"===_.Ma.readyState&&f.apply(this,arguments)}),_.Q.attachEvent("onload",f))}};
_.oc=function(){function a(c){c=c||window.event;var f=c.screenX+c.clientX<<16,f=f+(c.screenY+c.clientY),f=f*((new window.Date).getTime()%1E6);m=m*f%q;0<g&&++h==g&&_.R.tt(window,"mousemove",a,_.t)}function c(a){var c=(0,_.mc)();c.update(a);return c.Ye()}var f=window.crypto;if(f&&"function"==typeof f.getRandomValues)return function(){var a=new window.Uint32Array(1);f.getRandomValues(a);return(0,window.Number)("0."+a[0])};var g=(0,_.O)("random/maxObserveMousemove");g==_.r&&(g=-1);var h=0,k=window.Math.random(),
m=1,q=1E6*(window.screen.width*window.screen.width+window.screen.height);0!=g&&_.R.Te(window,"mousemove",a,_.t);var s=c(window.document.cookie+"|"+window.document.location+"|"+(new window.Date).getTime()+"|"+k);return function(){var a=m,a=a+(0,window.parseInt)(s.substr(0,20),16);s=c(s);return a/(q+window.Math.pow(16,20))}}();
(0,_.P)("shindig.random",_.oc);
_.Ul=function(a,c){var f=_.R.ai({id:a,name:a});f.style.width="1px";f.style.height="1px";f.style.position="absolute";f.style.top="-100px";var g;if(window.navigator){g=window.navigator.userAgent||"";var h=window.navigator.product||"";g=0!=g.indexOf("Opera")&&-1==g.indexOf("WebKit")&&"Gecko"==h&&0<g.indexOf("rv:1.")}else g=_.t;f.src=g?"about:blank":c;window.document.body.appendChild(f);g&&(f.src=c);return f};_.Vl={};
_.Wl=function(){function a(a,c,f,g){for(var h=0;h<M.length;h++){var k=M[h];window.setTimeout(function(){k(a,c,f,g)},1)}}function c(a,c,f,g){var h=s("proxy");if(f||!h)var h=s("root"),k=s("root-1p")||h,m=s("xd3"),h=(f||(0,window.String)(c?k:h))+m;(c=_.R.la().jsh||_.jc.Vh.ol())&&(h+=(0<=h.indexOf("?")?"&":"?")+"jsh="+(0,window.encodeURIComponent)(c));s("push")&&(h+=(0<=h.indexOf("?")?"&":"?")+"p=1");h+="#parent="+(0,window.encodeURIComponent)(g!=_.r?(0,window.String)(g):_.jc.ja(window.document.location.href));
return h+="&rpctoken="+a}function f(c,f,g,m){var q=h(g,m),s=(0,_.Ul)(q,f);_.S.I("ready:"+c,function(){_.S.Xd("ready:"+c);if(!z[q]){z[q]=_.p;var f=D[q];D[q]=[];for(var h=0,s=f.length;h<s;++h){var v=f[h];k(v.Df,v.At,v.Va)}a("ready",(new window.Date).getTime(),g,m||_.r)}});_.S.Gf(q,f);w[q]=s}function g(g,h){var k=(0,window.String)(2147483647*(0,_.oc)()|0),m=c(k,g,h);a("loading",(new window.Date).getTime(),g,h||_.r);(0,_.nc)(function(){f(k,m,g,h)})}function h(a,f){var g=c("",a,f,""),h=v[g];h||(h=(0,_.mc)(),
h.update(g),h=h.Ye().toLowerCase(),h+=window.Math.random(),v[g]=h);return"apiproxy"+h}function k(a,c,f){function k(a){a&&(q=a.root||q,s=_.Vk.cs(a.headers))}var q=_.r,s=_.t;if("makeRequest"===a||"listen"===a)k(c);else if("makeHttpRequests"===a&&c){for(var v=(0,_.O)("client/jsonpOverride"),M=0,jb=c.length;M<jb;++M){var bb=c[M];bb&&(bb=bb.params,k(bb),v&&m(bb,f))}if(v)return}v=h(s,q);w[v]||g(s,q);z[v]?_.S.call(v,a,function(c){var g=_.Zb.parse(c);if("makeRequest"==a&&g){for(var h={},k=0;k<g.length;k++)h[g[k].id]=
g[k];f(h,c)}else f(g,c)},c):(D[v]||(D[v]=[]),D[v].push({Df:a,At:c,Va:f}))}function m(a,c){"GET"!=a.httpMethod&&(0,_.l)("JSONP supports GET methods only.");var f="jpcb"+(0,window.String)(2147483647*(0,_.oc)()|0),g=window.document.createElement("script"),h=window.document.getElementsByTagName("head")[0];window[f]=function(a){c(a);try{delete window[f]}catch(k){window[f]=_.n}window.setTimeout(function(){h.removeChild(g)},1)};var k=a.root||s("root"),k=k+a.url,m=a.urlParams;if(m)for(var v in m)window.Object.prototype.hasOwnProperty.call(m,
v)&&(k=q(k,v,m[v]));k=q(k,"callback",f);g.setAttribute("id",f);g.setAttribute("src",k);g.setAttribute("charset","utf-8");h.appendChild(g)}function q(a,c,f){a+=0<a.indexOf("?")?"&":"?";return a+=(0,window.encodeURIComponent)(c)+"="+(0,window.encodeURIComponent)(f)}function s(a){return(0,_.O)("googleapis.config/"+a)}var v={},w={},z={},D={},M=[];return{ae:function(a,c){var f=a||{},g=_.jc.ja((0,window.String)(window.location.href));f["X-Origin"]=g;var g=f.Authorization,h=f.OriginToken;if(g==_.r&&h==_.r){if(g==
_.r){var k;_.Uk&&_.Vl&&(k=(0,_.ol)());k&&k.access_token&&(g=(0,window.String)(k.token_type||"Bearer")+" "+k.access_token)}g==_.r&&(s("auth/useFirstPartyAuth")&&_.Vk.vs())&&(k=f["X-Goog-AuthUser"],k==_.r&&(k=_.google.pr(c)||"0"),(g=_.Vk.af())&&(f["X-Goog-AuthUser"]=k));g?f.Authorization=g:s("auth/useOriginToken")!==_.t&&(h=_.Vk.hr())&&(f.OriginToken=h)}return f},Sp:function(a){M.push(a)},wt:function(a){for(var c=0;c<M.length;c++)if(M[c]==a){M.splice(c,1);break}},Sd:k}}();

_.xn=window.tamings___||[];_.yn=window.caja___;_.___=window.___;
_.zn=function(a,c,f){this.method=a;this.transport=c;this.rpc=f};
_.L.pj=function(){function a(a){var c={method:a.request.method,id:a.key};a.request.rpc&&(c.params=a.request.rpc);return c}var c={},f=[];c.execute=function(c){function h(a){a.error&&(k.error=a.error);for(var h=0;h<f.length;h++){var m=f[h].key,s=a[m];s&&(k[m]=s.error?s:s.data||s.result)}q--;0===q&&c(k)}for(var k={},m={},q=0,s=[],v=0;v<f.length;v++){var w=f[v].request.transport;m[w.name]||(s.push(w),q++);m[w.name]=m[w.name]||[];m[w.name].push(a(f[v]))}for(v=0;v<s.length;v++)s[v].execute(m[s[v].name], h);0==q&&window.setTimeout(function(){c(k)},0)};c.add=function(a,h){h&&a&&f.push({key:a,request:h});return c};return c};
_.L.Oh=function(a,c){if("newBatch"!==a){for(var f=a.split("."),g=window.osapi,h=0;h<f.length-1;h++)g[f[h]]=g[f[h]]||{},g=g[f[h]];var k=f[f.length-1];g[k]?(g.__dupwarn||(0,_.ta)("Skipping duplicate osapi method definition "+a+" on transport "+c.name+"; others may exist, but suppressing warnings"),g.__dupwarn=_.p):(g[k]=function(f){f=f||{};f.userId=f.userId||"@viewer";f.groupId=f.groupId||"@self";return new _.zn(a,c,f)},"undefined"!==typeof _.xn&&_.xn.push(function(){_.yn.markTameAsFunction(g[k],a)}))}};
_.zn.prototype.execute=function(a){var c="undefined"!==typeof _.yn&&_.yn.getUseless&&_.yn.getUseless(),f=c?_.yn.getUseless():this,g=c?_.yn.untame(a):a;a=_.L.pj();a.add(this.method,this);a.execute(function(a){a.error?g.call(f,a.error):g.call(f,a[f.method])})};

_.An=function(a,c){for(var f=a.split("."),g=c||window,h;h=f.shift();)if(g[h]!=_.r)g=g[h];else return _.r;return g};_.Bn=function(a,c,f){a=a.split(".");f=f||window;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&c!==_.n?f[g]=c:f=f[g]?f[g]:f[g]={}};
_.Cn=function(a,c){_.L.Oh(a,{name:"googleapis",execute:_.Dn,root:c});var f=(0,_.An)(a,window.osapi);(0,_.Bn)(a,f);if(0!=a.indexOf("googleapis.")){var g=a.substring(a.indexOf(".")+1),h=g.lastIndexOf(".delete");-1!=h&&h+7==g.length&&(g=g.replace(".delete",".remove"));(0,_.Bn)("googleapis."+g,f)}};_.En=function(a){for(var c in a)a.hasOwnProperty(c)&&(_.Fn[c]=a[c])};_.Gn=function(a){(0,_.Hn)("key",a)};_.Hn=function(a,c){c==_.r?(0,_.In)(a):(_.Jn=_.Jn||{},_.Jn[a]=c)};_.In=function(a){_.Jn&&delete _.Jn[a]};
_.Kn=function(a){a=a||{};if(window.navigator){for(var c=["appVersion","platform","userAgent"],f=[],g=0;g<c.length;g++)window.navigator[c[g]]&&f.push((0,window.encodeURIComponent)(c[g])+"="+(0,window.encodeURIComponent)(window.navigator[c[g]]));a["X-ClientDetails"]=f.join("&")}return a};
_.Ln=function(a,c){for(var f=0;f<_.Mn.length;f++)window.setTimeout(function(c){return function(){c(a)}}(_.Mn[f]),1);return function(){var a=arguments;c.apply(_.r,a);for(var f=0;f<_.Nn.length;f++)window.setTimeout(function(c){return function(){c.apply(_.r,a)}}(_.Nn[f]),1)}};_.On=function(a){a.applicationName=_.Pn;a.clientVersion="1.0.0-alpha";_.Jn&&(a.urlParams=_.Jn,_.Jn.key&&(a.developerKey=_.Jn.key))};
_.Dn=function(a,c){for(var f=this.root||_.r,g=0;g<a.length;g++){var h=a[g],k=h.method.substring(0,h.method.indexOf("."));h.jsonrpc="2.0";h.key=h.id;f=h.root||f;(k=_.Fn[k]||"v1")&&!h.apiVersion&&(h.apiVersion=k)}g={};g=_.Wl.ae(g);g=(0,_.Kn)(g);f={requests:a,headers:g,root:f};(0,_.On)(f);g=(0,_.Ln)(a,c);_.Wl.Sd("makeRequest",f,g)};_.Qn=function(a){_.Mn.push(a)};_.Rn=function(a){_.Nn.push(a)};_.Sn=function(a){for(var c=0;c<_.Mn.length;c++)if(_.Mn[c]==a){_.Mn.splice(c,1);break}};
_.Tn=function(a){for(var c=0;c<_.Nn.length;c++)if(_.Nn[c]==a){_.Nn.splice(c,1);break}};_.Un=function(a,c){for(var f=0,g=a.length;f<g;f++){var h=a[f];h.key=h.id;var k=h.params.headers||{},k=_.Wl.ae(k),k=(0,_.Kn)(k);h.params.headers=k;(0,_.On)(h.params)}f=(0,_.Ln)(a,c);_.Wl.Sd("makeHttpRequests",a,f)};
_.Vn=function(){var a=_.R.la(),c={debug:"googleapis.config/debug"},f;for(f in c)a[f]&&(0,_.Ja)(c[f],"true"==a[f]);for(var g in(0,_.O)("googleapis.config/methods"))(0,_.Cn)(g);(0,_.O)("googleapis.config/versions")&&(0,_.En)((0,_.O)("googleapis.config/versions"));(0,_.O)("googleapis.config/developerKey")&&(0,_.Gn)((0,_.O)("googleapis.config/developerKey"));_.L.Oh("googleapis.newHttpRequest",{name:"googleapis",execute:_.Un});(0,_.Bn)("googleapis.newHttpRequest",(0,_.An)("googleapis.newHttpRequest",window.osapi))}; _.Wn=function(){this.d={};this.b=_.L.pj()};
_.Pn=_.r;_.Fn={};_.Mn=[];_.Nn=[];(0,_.Vn)();_.Wn.prototype.add=function(a,c,f){this.d[a]=f;this.b.add(a,c);return this};_.Wn.prototype.execute=function(a){var c=this;this.b.execute(function(f){var g={},h=_.t,k;for(k in f)if(f.hasOwnProperty(k)){var m=f[k],q=c.d[k];q?q(m):(g[k]=m,h=_.p)}h&&a&&a(g)})};
(0,_.P)("googleapis.ApiClient.register",_.Cn);(0,_.P)("googleapis.ApiClient.setVersions",_.En);(0,_.P)("googleapis.ApiClient.setDeveloperKey",_.Gn);(0,_.P)("googleapis.ApiClient.setUrlParameter",_.Hn);(0,_.P)("googleapis.ApiClient.removeUrlParameter",_.In);(0,_.P)("googleapis.ApiClient.addExecuteListener",_.Qn);(0,_.P)("googleapis.ApiClient.addResponseListener",_.Rn);(0,_.P)("googleapis.ApiClient.removeExecuteListener",_.Sn);(0,_.P)("googleapis.ApiClient.removeResponseListener",_.Tn);
(0,_.P)("googleapis.ApiClient.init",_.Vn);(0,_.P)("googleapis.Batch",_.Wn);(0,_.P)("googleapis.Batch.prototype.add",_.Wn.prototype.add);(0,_.P)("googleapis.Batch.prototype.execute",_.Wn.prototype.execute);(0,_.P)("googleapis.init",function(){(0,_.Vn)()});(0,_.P)("googleapis.newBatch",function(){return new _.Wn});
(0,_.P)("googleapis.newRequest",function(a,c,f){c=c||{};var g={name:"googleapis",execute:_.Dn,root:f},h=_.L.pj(),k=this;f={};f.method=a;f.transport=g;f.rpc=c;f.execute=function(f){h.add(a,{method:a,rpc:c,transport:g});h.execute(function(c){c.error?f.call(k,c.error):f.call(k,c[a])})};return f});(0,_.P)("googleapis.register",function(a,c){(0,_.Cn)(a,c)});(0,_.P)("googleapis.setUrlParameter",function(a,c){(0,_.Hn)(a,c)});(0,_.P)("googleapis.removeUrlParameter",function(a){(0,_.In)(a)});
(0,_.P)("googleapis.setDeveloperKey",function(a){(0,_.Gn)(a)});(0,_.P)("googleapis.setApplicationName",function(a){_.Pn=a});(0,_.P)("googleapis.setVersions",function(a){(0,_.En)(a)});(0,_.P)("googleapis.addExecuteListener",function(a){(0,_.Qn)(a)});(0,_.P)("googleapis.removeExecuteListener",function(a){(0,_.Sn)(a)});(0,_.P)("googleapis.addResponseListener",function(a){(0,_.Rn)(a)});(0,_.P)("googleapis.removeResponseListener",function(a){(0,_.Tn)(a)}); (0,_.P)("googleapis.addTransportInitListener",function(a){_.Wl.Sp(a)});(0,_.P)("googleapis.removeTransportInitListener",function(a){_.Wl.wt(a)});

_.Ya={go:{},J:{}};_.Za={go:{},J:{}};


_.cb=function(a,c){var f=[];if(a)for(var g in a)if((0,_.Ua)(a,g)&&a[g]!=_.r){var h=c?c(a[g]):a[g];f.push((0,window.encodeURIComponent)(g)+"="+(0,window.encodeURIComponent)(h))}return f};_.db=function(a){return a.$p+(0<a.Fe.length?"?"+a.Fe.join("&"):"")+(0<a.lg.length?"#"+a.lg.join("&"):"")};_.eb=function(a){a=a.match(_.fb);var c=(0,_.N)();c.$p=a[1];c.Fe=a[3]?[a[3]]:[];c.lg=a[5]?[a[5]]:[];return c};
_.gb=function(a,c,f,g){a=(0,_.eb)(a);a.Fe.push.apply(a.Fe,(0,_.cb)(c,g));a.lg.push.apply(a.lg,(0,_.cb)(f,g));return(0,_.db)(a)};_.hb=function(a,c){a||(0,_.l)((0,window.Error)(c||""))};_.lb=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.mb=function(a){return(0,window.String)(a).replace(_.nb,"&amp;").replace(_.ob,"&lt;").replace(_.pb,"&gt;").replace(_.qb,"&quot;").replace(_.rb,"&#39;")};_.sb=function(){};
_.tb=function(){this.b=[];this.j=[];this.o=[];this.i=[];this.i[0]=128;for(var a=1;64>a;++a)this.i[a]=0;this.reset()};
_.ub=function(a,c,f){f||(f=0);var g=a.o;if((0,_.F)(c))for(var h=0;16>h;h++)g[h]=c.charCodeAt(f)<<24|c.charCodeAt(f+1)<<16|c.charCodeAt(f+2)<<8|c.charCodeAt(f+3),f+=4;else for(h=0;16>h;h++)g[h]=c[f]<<24|c[f+1]<<16|c[f+2]<<8|c[f+3],f+=4;for(h=16;80>h;h++){var k=g[h-3]^g[h-8]^g[h-14]^g[h-16];g[h]=(k<<1|k>>>31)&4294967295}c=a.b[0];f=a.b[1];for(var m=a.b[2],q=a.b[3],s=a.b[4],v,h=0;80>h;h++)40>h?20>h?(k=q^f&(m^q),v=1518500249):(k=f^m^q,v=1859775393):60>h?(k=f&m|q&(f|m),v=2400959708):(k=f^m^q,v=3395469782),
k=(c<<5|c>>>27)+k+s+v+g[h]&4294967295,s=q,q=m,m=(f<<30|f>>>2)&4294967295,f=c,c=k;a.b[0]=a.b[0]+c&4294967295;a.b[1]=a.b[1]+f&4294967295;a.b[2]=a.b[2]+m&4294967295;a.b[3]=a.b[3]+q&4294967295;a.b[4]=a.b[4]+s&4294967295};_.vb=function(a){a=a||_.Q.event;var c=a.screenX+a.clientX<<16,c=c+(a.screenY+a.clientY),c=c*((new window.Date).getTime()%1E6);_.wb=_.wb*c%_.xb;0<_.yb&&++_.zb==_.yb&&(0,_.Wa)(_.Q,"mousemove",_.vb,"remove","de")};
_.Ab=function(a){var c=new _.tb;c.update(a);a=c.Wk();for(var c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(window.Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c};_.Bb=function(){var a=_.wb,a=a+(0,window.parseInt)(_.Cb.substr(0,20),16);_.Cb=(0,_.Ab)(_.Cb);return a/(_.xb+window.Math.pow(16,20))};_.Db=function(){var a=new _.Q.Uint32Array(1);_.Eb.getRandomValues(a);return(0,window.Number)("0."+a[0])};
_.Fb=function(){var a=_.Aa.onl;if(!a){a=(0,_.N)();_.Aa.onl=a;var c=(0,_.N)();a.e=function(a){var g=c[a];g&&(delete c[a],g())};a.a=function(a,g){c[a]=g};a.r=function(a){delete c[a]}}return a};_.Gb=function(a,c){var f=c.onload;return"function"===typeof f?((0,_.Fb)().a(a,f),f):_.r};_.Hb=function(a){(0,_.hb)(/^\w+$/.test(a),"Unsupported id - "+a);(0,_.Fb)();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};_.Ib=function(a){(0,_.Fb)().r(a)};
_.Jb=function(a,c){var f,g=0;do f=c.id||["I",_.Kb++,"_",(new window.Date).getTime()].join("");while(a.getElementById(f)&&5>++g);(0,_.hb)(5>g,"Error creating iframe id");return f};
_.Lb=function(a,c,f,g){var h={},k={};(0,_.Va)(g.queryParams||{},h);(0,_.Va)(g.fragmentParams||{},k);var m=(0,_.N)();m.id=f;m.parent=a.location.protocol+"//"+a.location.host;f=(0,_.xa)(a.location.href,"id","");var q=(0,_.xa)(a.location.href,"pfname","");(f=f?q+"/"+f:"")&&(m.pfname=f);(0,_.Va)(m,k);(m=(0,_.xa)(c,"rpctoken")||h.rpctoken||k.rpctoken)||(m=k.rpctoken=g.rpctoken||(0,window.String)(window.Math.round(1E8*(_.Mb?(0,_.Db)():(0,_.Bb)()))));g.rpctoken=m;m=a.location.href;a=(0,_.N)();(f=(0,_.xa)(m,
"_bsh",_.Aa.bsh))&&(a._bsh=f);(m=!_.Aa.dpo?(0,_.xa)(m,"jsh",_.Aa.h):_.Aa.h)&&(a.jsh=m);g.hintInFragment?(0,_.Va)(a,k):(0,_.Va)(a,h);return(0,_.gb)(c,h,k,g.paramsSerializer)};_.Nb=function(a){(0,_.hb)(!a||_.Ob.test(a),"Illegal url for new iframe - "+a)};
_.Qb=function(a,c,f,g,h){(0,_.Nb)(f.src);var k,m=(0,_.Gb)(g,f),q=m?(0,_.Hb)(g):"";try{k=a.createElement('<iframe frameborder="'+(0,_.mb)((0,window.String)(f.frameborder))+'" scrolling="'+(0,_.mb)((0,window.String)(f.scrolling))+'" '+q+' name="'+(0,_.mb)((0,window.String)(f.name))+'"/>')}catch(s){k=a.createElement("iframe"),m&&(k.onload=function(){k.onload=_.r;m.call(this)},(0,_.Ib)(g))}for(var v in f)a=f[v],"style"===v&&"object"===typeof a?(0,_.Va)(a,k.style):_.Rb[v]||k.setAttribute(v,(0,window.String)(a));
v=h&&h.beforeNode||_.r;!v&&(!h||!h.dontclear)&&(0,_.lb)(c);c.insertBefore(k,v);k=v?v.previousSibling:c.lastChild;f.allowtransparency&&(k.allowTransparency=_.p);return k};_.Sb=function(a,c){if(!_.Tb){var f=(0,_.O)("iframes/:socialhost:"),g=(0,_.$a)(_.n)||"0",h=(0,_.$a)(_.n);_.Tb={socialhost:f,session_index:g,session_prefix:h!==_.n&&h!==_.r&&""!==h?"u/"+h+"/":"",im_prefix:(0,_.O)("googleapis.config/signedIn")===_.t?"_/im/":""}}return _.Tb[c]||""};
_.Ub=function(a){return(0,_.ya)(_.Ma,a.replace(_.Vb,_.Sb))};
_.Wb=function(a,c,f){var g=f||{};f=g.attributes||{};(0,_.hb)(!g.allowPost||!f.onload,"onload is not supported by post iframe");var h=f=a;_.Xb.test(f)&&(h=(0,_.O)("iframes/"+h.substring(1)+"/url"),(0,_.hb)(!!h,"Unknown iframe url config for - "+f));a=(0,_.Ub)(h);f=c.ownerDocument||_.Ma;h=(0,_.Jb)(f,g);a=(0,_.Lb)(f,a,h,g);var k=(0,_.N)();(0,_.Va)(_.Yb,k);(0,_.Va)(g.attributes,k);k.name=k.id=h;k.src=a;if((g||{}).allowPost&&2E3<a.length){var m=(0,_.eb)(a);k.src="";k["data-postorigin"]=a;a=(0,_.Qb)(f,
c,k,h);var q;if(-1!=window.navigator.userAgent.indexOf("WebKit")){q=a.contentWindow.document;q.open();var k=q.createElement("div"),s={},v=h+"_inner";s.name=v;s.src="";s.style="display:none";(0,_.Qb)(f,k,s,v,g)}k=(g=m.Fe[0])?g.split("&"):[];g=[];for(s=0;s<k.length;s++)v=k[s].split("=",2),g.push([(0,window.decodeURIComponent)(v[0]),(0,window.decodeURIComponent)(v[1])]);m.Fe=[];k=(0,_.db)(m);m=f.createElement("form");m.action=k;m.method="POST";m.target=h;m.style.display="none";for(h=0;h<g.length;h++)k=
f.createElement("input"),k.type="hidden",k.name=g[h][0],k.value=g[h][1],m.appendChild(k);c.appendChild(m);m.submit();m.parentNode.removeChild(m);q&&q.close();c=a}else c=(0,_.Qb)(f,c,k,h,g);return c};_.fb=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.Ob=/^https?:\/\/[^\/%\\?#\s]+\/[^\s]*$/i;_.rb=/'/g;_.qb=/"/g;_.pb=/>/g;_.ob=/</g;_.nb=/&/g;
(0,_.K)(_.tb,_.sb);_.tb.prototype.reset=function(){this.b[0]=1732584193;this.b[1]=4023233417;this.b[2]=2562383102;this.b[3]=271733878;this.b[4]=3285377520;this.k=this.d=0};_.tb.prototype.update=function(a,c){(0,_.E)(c)||(c=a.length);for(var f=c-64,g=0,h=this.j,k=this.d;g<c;){if(0==k)for(;g<=f;)(0,_.ub)(this,a,g),g+=64;if((0,_.F)(a))for(;g<c;){if(h[k]=a.charCodeAt(g),++k,++g,64==k){(0,_.ub)(this,h);k=0;break}}else for(;g<c;)if(h[k]=a[g],++k,++g,64==k){(0,_.ub)(this,h);k=0;break}}this.d=k;this.k+=c};
_.tb.prototype.Wk=function(){var a=[],c=8*this.k;56>this.d?this.update(this.i,56-this.d):this.update(this.i,64-(this.d-56));for(var f=63;56<=f;f--)this.j[f]=c&255,c/=256;(0,_.ub)(this,this.j);for(f=c=0;5>f;f++)for(var g=24;0<=g;g-=8)a[c]=this.b[f]>>g&255,++c;return a};
_.Eb=_.Q.crypto;_.Mb=_.t;_.yb=0;_.zb=0;_.wb=1;_.xb=0;_.Cb="";_.Mb=!!_.Eb&&"function"==typeof _.Eb.getRandomValues;_.Mb||(_.xb=1E6*(window.screen.width*window.screen.width+window.screen.height),_.Cb=(0,_.Ab)(_.Ma.cookie+"|"+_.Ma.location+"|"+(new window.Date).getTime()+"|"+window.Math.random()),_.yb=(0,_.O)("random/maxObserveMousemove")||0,0!=_.yb&&(0,_.Xa)(_.Q,"mousemove",_.vb));
_.Yb={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};_.Rb={allowtransparency:_.p,onload:_.p};_.Kb=0;_.Xb=/^:[\w]+$/;_.Vb=/:([a-zA-Z_]+):/g;
_.R=_.R||{};_.R.Rg=function(a,c,f){for(var g=[],h=2,k=arguments.length;h<k;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,k=arguments.length;h<k;++h)f.push(arguments[h]);return c.apply(a,f)}};_.R.Bf=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};

_.bc=_.bc||{};_.bc.tr=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};

_.cc=function(a){return!!a&&"object"===typeof a&&_.wa.test(a.push)};_.dc=function(a){for(var c=0;c<this.length;c++)if(this[c]===a)return c;return-1};_.bc=_.bc||{};
(function(){function a(a,f){window.getComputedStyle(a,"").getPropertyValue(f).match(/^([0-9]+)/);return(0,window.parseInt)(window.RegExp.$1,10)}_.bc.ef=function(){var c=_.bc.tr().height,f=window.document.body,g=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&g.scrollHeight)return g.scrollHeight!==c?g.scrollHeight:g.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){c=0;for(f=[window.document.body];0<f.length;){var h=f.shift(),g=h.childNodes;if("undefined"!==
typeof h.style){var k=h.style.overflowY;k||(k=(k=window.document.defaultView.getComputedStyle(h,_.r))?k.overflowY:_.r);if("visible"!=k&&"inherit"!=k&&(k=h.style.height,k||(k=(k=window.document.defaultView.getComputedStyle(h,_.r))?k.height:""),0<k.length&&"auto"!=k))continue}for(h=0;h<g.length;h++){k=g[h];if("undefined"!==typeof k.offsetTop&&"undefined"!==typeof k.offsetHeight)var m=k.offsetTop+k.offsetHeight+a(k,"margin-bottom"),c=window.Math.max(c,m);f.push(k)}}return c+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(f&&g)return h=g.scrollHeight,k=g.offsetHeight,g.clientHeight!==k&&(h=f.scrollHeight,k=f.offsetHeight),h>c?h>k?h:k:h<k?h:k}})();

_.kc=window.iframer=window.iframer||{};_.T=window.iframes=window.iframes||{};
_.T.gq=function(a,c,f){var g=window.Array.prototype.slice.call(arguments);_.T.pl(function(a){a.sameOrigin&&(g.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.S.call.apply(_.S,g))})};_.T.ot=function(a,c){_.S.I(a,c)};

_.T.O=_.T.O||{};_.T.O.hq=function(a){try{return!!a.document}catch(c){}return _.t};_.T.O.vl=function(a){var c=a.parent;return a!=c&&_.T.O.hq(c)?_.T.O.vl(c):a};_.T.O.ny=function(a){var c=a.userAgent||"";a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};

_.pc=function(a){_.T.ih[a]||(_.T.ih[a]={},_.S.I(a,function(c,f){var g=this.f;if("string"==typeof c&&!(c in{})&&!(g in{})){var h=this.callback,k=_.T.ih[a][g],m;k&&window.Object.hasOwnProperty.call(k,c)?m=k[c]:window.Object.hasOwnProperty.call(_.T.re,a)&&(m=_.T.re[a]);if(m)return g=window.Array.prototype.slice.call(arguments,1),m._iframe_wrapped_rpc_&&h&&g.push(h),m.apply({},g)}(0,_.ua)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',g,'".'].join(""));
return _.r}));return _.T.ih[a]};_.qc=function(a,c,f){function g(g){var k=window.Array.prototype.slice.call(arguments,0),m=k[k.length-1];if("function"===typeof m){var q=m;k.pop()}k.unshift(c,a,q,f);_.S.call.apply(_.S,k)}g._iframe_wrapped_rpc_=_.p;return g};_.rc=function(){window.setTimeout(function(){_.S.call("..","_noop_echo",_.T.$s)},0)};_.sc=function(){_.S.I("_noop_echo",function(){this.callback(_.T.gr(_.T.od[this.f]))})};_.tc=function(a,c){var f=(0,_.va)(_.Aa,"watt",(0,_.N)());(0,_.va)(f,a,c)};
_.uc=function(){return _.Q.location.origin||_.Q.location.protocol+"//"+_.Q.location.host};_.vc=function(a){var c=(0,_.xa)(a.location.href,"urlindex");if(c=(0,_.va)(_.Aa,"fUrl",[])[c]){var f=a.location.hash,c=c+(/#/.test(c)?f.replace(/^#/,"&"):f);a.location.replace(c)}};_.wc=function(){_.T.im++;return["I",_.T.im,"_",(new window.Date).getTime()].join("")};_.xc=function(a){return a instanceof window.Array?a.join(","):a instanceof window.Object?_.Zb.stringify(a):a};_.yc=function(){};
_.zc=function(a){a&&a.match(_.Ac)&&(0,_.Ja)("googleapis.config/gcv",a)};_.Bc=function(a){_.jc.Vh.$t(a)};_.Cc=function(a){_.jc.Vh.Oj(a)};_.Dc=function(a,c){var f=c||{},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);return f};_.Ec=function(a,c,f,g,h){var k=[],m;for(m in a)if(a.hasOwnProperty(m)){var q=c,s=f,v=a[m],w=g,z=(0,_.pc)(m);z[q]=z[q]||{};w=_.R.Rg(w,v);v._iframe_wrapped_rpc_&&(w._iframe_wrapped_rpc_=_.p);z[q][s]=w;k.push(m)}if(h)for(m in _.T.re)_.T.re.hasOwnProperty(m)&&k.push(m);return k.join(",")};
_.Fc=function(a,c,f){var g={};if(a&&a._methods){a=a._methods.split(",");for(var h=0;h<a.length;h++){var k=a[h];g[k]=(0,_.qc)(k,c,f)}}return g};_.Gc=function(a){return a&&a.disableMultiLevelParentRelay?_.t:_.kc&&_.kc._open&&"inline"!=a.style&&a.inline!==_.p&&!(a.container&&("string"==typeof a.container&&window.document.getElementById(a.container)||window.document==(a.container.ownerDocument||a.container.document)))};
_.Hc=function(a,c){var f={},g=c.params||{},h;for(h in a)"#"==h.charAt(0)&&(f[h.substring(1)]=a[h]),0==h.indexOf("fr-")&&(f[h.substring(3)]=a[h]),"#"==g[h]&&(f[h]=a[h]);for(var k in f)delete a["fr-"+k],delete a["#"+k],delete a[k];return f};_.Ic=function(a){if(":"==a.charAt(0)){var c=(0,_.O)("iframes/"+a.substring(1));a={};(0,_.Va)(c,a);(c=a.url)&&(a.url=(0,_.Ub)(c));a.params||(a.params={});return a}return{url:(0,_.Ub)(a)}};_.Jc=function(a,c){function f(){}f.prototype=c.prototype;a.prototype=new f};
_.Kc=function(a,c,f,g,h,k,m,q){this.xa=(0,_.Ic)(a);this.openParams=this.k=c;this.Sa=f||{};this.Za=g;this.o=_.t;(0,_.Lc)(this,c.style);this.d={};(0,_.Mc)(this,function(){var a;(a=this.k.style)&&_.T.Kf[a]?a=_.T.Kf[a]:a?((0,_.ta)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=_.r):a=_.Nc;if(a){var c;if("function"===typeof a)c=a(this);else{var f={};for(c in a){var g=a[c];f[c]="function"===typeof g?_.R.Rg(a,g,this):g}c=f}for(var m in h)a=c[m],"function"===typeof a&&
(0,_.Oc)(this,h[m],_.R.Rg(c,a))}k&&(0,_.Oc)(this,"close",k)});this.Uc=this.ac=m;this.zj=(q||[]).slice();m&&this.zj.unshift(m.da())};_.Lc=function(a,c){if(!a.o){var f=c&&!_.T.Kf[c]&&_.T.ci[c];f?(a.u=[],f(function(){a.o=_.p;for(var c=0,f=a.u.length;c<f;++c)a.u[c].call(a)})):a.o=_.p}};_.Mc=function(a,c){a.o?c.call(a):a.u.push(c)};_.Oc=function(a,c,f){a.d[c]=a.d[c]||[];a.d[c].push(f)};_.Pc=function(a,c){return"number"==typeof c?{value:c,Ed:c+"px"}:"100%"==c?{value:100,Ed:"100%",xm:_.p}:_.r};
_.Qc=function(a,c,f,g,h,k,m){_.Kc.call(this,a,c,f,g,_.Rc,h,k,m);this.id=c.id||(0,_.wc)();this.i=c.rpcToken||window.Math.round(1E9*(0,_.oc)());this.L=(0,_.Hc)(this.Sa,this.xa);this.C={};(0,_.Mc)(this,function(){this.Sb("open");(0,_.Dc)(this.C,this)})};
_.Sc=function(a,c,f,g,h,k,m){_.Kc.call(this,a,c,f,g,_.Tc,h,k,m);this.url=a;this.b=_.r;this.G=(0,_.wc)();(0,_.Mc)(this,function(){this.Sb("beforeparentopen");var a=(0,_.Dc)(this.Za);a._onopen=this.ia;a._ready=this.Yg;a._onclose=this.W;this.Sa._methods=(0,_.Ec)(a,"..",this.G,this,_.p);var a={},c;for(c in this.Sa)a[c]=(0,_.xc)(this.Sa[c]);var f=this.xa.url;if(this.k.hideUrlFromParent){c=window.name;var g=f,f=(0,_.gb)(this.xa.url,this.Sa,{},_.xc),h=a,a={};a._methods=h._methods;a["#opener"]=h["#opener"];
a["#urlindex"]=h["#urlindex"];a["#opener"]&&h["#urlindex"]!=_.n?(a["#opener"]=c+","+a["#opener"],c={url:g,Sa:a}):(g=(0,_.va)(_.Aa,"fUrl",[]),h=g.length,g[h]=f,_.Aa.rUrl=_.vc,a["#opener"]=c,a["#urlindex"]=h,c=_.jc.ja(_.Q.location.href),f=(0,_.O)("iframes/relay_url_"+(0,window.encodeURIComponent)(c))||"/_/gapi/sibling/1/frame.html",c={url:c+f,Sa:a});f=c.url;a=c.Sa}_.kc._open({url:f,openParams:this.k,params:a,proxyId:this.G,openedByProxyChain:this.zj})})};
_.Uc=function(a,c,f,g,h,k,m){_.Kc.call(this,a,c,f,g,_.Tc,k,m);this.id=c.id||(0,_.wc)();this.i=h;g._close=this.close;this.onClosed=this.b;this.K=0;(0,_.Mc)(this,function(){this.Sb("beforeparentopen");var c=(0,_.Dc)(this.Za);this.Sa._methods=(0,_.Ec)(c,"..",this.G,this,_.p);c={};c.queryParams=this.Sa;a=_.Vc.jy(_.Ma,this.xa.url,this.id,c);var f=h.Um(a);this.canAutoClose=function(a){a(h.Qk(f))};h.Ln(f,this);this.K=f})};_.Wc=function(a){return _.T.Kf[a]};_.Xc=function(a,c){_.T.Kf[a]=c}; _.Yc=function(a){a=a||{};"auto"===a.height&&(a.height=_.bc.ef());var c=window&&_.Zc&&_.Zc.va();c?c.tn(a.width||0,a.height||0):_.kc&&_.kc._resizeMe&&_.kc._resizeMe(a)};_.$c=function(a){(0,_.zc)(a)};_.Vc={};
if(window.ToolbarApi)_.Zc=window.ToolbarApi,_.Zc.va=window.ToolbarApi.getInstance,_.Zc.prototype=window.ToolbarApi.prototype,_.A=_.Zc.prototype,_.A.Um=_.Zc.prototype.openWindow,_.A.Sk=_.Zc.prototype.closeWindow,_.A.Ln=_.Zc.prototype.setOnCloseHandler,_.A.Qk=_.Zc.prototype.canClosePopup,_.A.tn=_.Zc.prototype.resizeWindow;else{_.ad=_.r;_.Zc=(0,_.u)();_.Zc.va=function(){!_.ad&&(window.external&&window.external.GTB_IsToolbar)&&(_.ad=new _.Zc);return _.ad};_.A=_.Zc.prototype;_.A.Um=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.A.Sk=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.A.Ln=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.A.Qk=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.A.tn=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=_.Zc;window.ToolbarApi.getInstance=_.Zc.va};
_.Ac=/^[-_.0-9A-Za-z]+$/;_.Rc={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"};_.Tc={onBeforeParentOpen:"beforeparentopen"};_.Nc={onOpen:function(a){var c=a.pa();a.Ra(c.container||c.element);return a},onClose:function(a){a.remove()}};_.T.$q=function(a){var c=(0,_.N)();(0,_.Va)(_.Yb,c);(0,_.Va)(a,c);return c};_.A=_.Kc.prototype;_.A.pa=(0,_.x)("k");_.A.wb=(0,_.x)("Sa");_.A.pg=(0,_.x)("Za");
_.A.Ga=(0,_.x)("Uc");_.A.na=function(a,c){(0,_.Mc)(this,function(){(0,_.Oc)(this,a,c)})};_.A.Xb=function(a,c){(0,_.Mc)(this,function(){var f=this.d[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};_.A.Sb=function(a,c){var f,g=this.d[a];if(g)for(var h=window.Array.prototype.slice.call(arguments,1),k=0,m=g.length;k<m;++k)try{f=g[k].apply({},h)}catch(q){(0,_.ua)(['Exception when calling callback "',a,'" with exception "',q.name,": ",q.message,'".'].join(""))}return f};
(0,_.Jc)(_.Qc,_.Kc);_.A=_.Qc.prototype;
_.A.Ra=function(a,c){if(!this.xa.url)return(0,_.ua)("Cannot open iframe, empty URL."),this;var f=this.id;_.T.od[f]=this;var g=(0,_.Dc)(this.Za);g._ready=this.Yg;g._close=this.close;g._open=this.Vm;g._resizeMe=this.uk;g._renderstart=this.Rm;var h=this.L;this.i&&(h.rpctoken=this.i);h._methods=(0,_.Ec)(g,f,"",this,_.p);this.j=a="string"===typeof a?window.document.getElementById(a):a;g={};g.id=f;if(c){g.attributes=c;var k=c.style;if("string"===typeof k){var m;if(k){m=[];for(var k=k.split(";"),q=0,s=k.length;q<
s;++q){var v=k[q];0==v.length&&q+1==s||(v=v.split(":"),2==v.length&&v[0].match(/^[ a-zA-Z_-]+$/)&&v[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?m.push(v.join(":")):(0,_.ua)(['Iframe style "',k[q],'" not allowed.'].join("")))}m=m.join(";")}else m="";c.style=m}}this.pa().allowPost&&(g.allowPost=_.p);g.queryParams=this.Sa;g.fragmentParams=h;g.paramsSerializer=_.xc;this.b=(0,_.Wb)(this.xa.url,a,g);h=this.b.getAttribute("data-postorigin")||this.b.src;_.T.od[f]=this;_.S.kh(this.id,this.i);_.S.Ac(this.id,h);return this};
_.A.Ca=function(a,c){this.C[a]=c};_.A.da=(0,_.x)("id");_.A.Z=(0,_.x)("b");_.A.V=(0,_.x)("j");_.A.Hb=(0,_.ba)("j");_.A.Yg=function(a){var c=(0,_.Fc)(a,this.id,"");this.Uc&&"function"==typeof this.Za._ready&&(a._methods=(0,_.Ec)(c,this.Uc.da(),this.id,this,_.t),this.Za._ready(a));(0,_.Dc)(a,this);(0,_.Dc)(c,this);this.Sb("ready",a)};_.A.Rm=function(a){this.Sb("renderstart",a)};_.A.close=function(a){a=this.Sb("close",a);delete _.T.od[this.id];return a};
_.A.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.A.Vm=function(a){var c=(0,_.Fc)(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.j);if((0,_.Gc)(a.openParams))new _.Sc(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else{var f=new _.Qc(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;(0,_.Mc)(f,function(){var a={childId:f.da()},k=f.C;k._toclose=f.close;a._methods=(0,_.Ec)(k,g.id,f.id,f,_.t);c._onopen(a)})}};
_.A.uk=function(a){if(this.Sb("resize",a)===_.n&&this.b){var c=(0,_.Pc)(this,a.width);c!=_.r&&(this.b.style.width=c.Ed);a=(0,_.Pc)(this,a.height);a!=_.r&&(this.b.style.height=a.Ed);if(this.b.parentElement&&(c!=_.r&&c.xm||a!=_.r&&a.xm))this.b.parentElement.style.display="block"}};(0,_.Jc)(_.Sc,_.Kc);_.Sc.prototype.i=(0,_.x)("b");
_.Sc.prototype.ia=function(a){this.b=a.childId;var c=(0,_.Fc)(a,"..",this.b);(0,_.Dc)(c,this);this.close=c._toclose;_.T.od[this.b]=this;this.Uc&&this.Za._onopen&&(a._methods=(0,_.Ec)(c,this.Uc.da(),this.b,this,_.t),this.Za._onopen(a))};_.Sc.prototype.Yg=function(a){var c=(0,window.String)(this.b),f=(0,_.Fc)(a,"..",c);(0,_.Dc)(a,this);(0,_.Dc)(f,this);this.Sb("ready",a);this.Uc&&this.Za._ready&&(a._methods=(0,_.Ec)(f,this.Uc.da(),c,this,_.t),this.Za._ready(a))};
_.Sc.prototype.W=function(a){if(this.Uc&&this.Za._onclose)this.Za._onclose(a);else return a=this.Sb("close",a),delete _.T.od[this.b],a};(0,_.Jc)(_.Uc,_.Kc);_.Uc.prototype.close=function(a){a=this.Sb("close",a);this.i.Sk(this.K);return a};_.Uc.prototype.b=function(){this.Sb("close")};
(function(){_.T.od={};_.T.Kf={};_.T.ci={};_.T.im=0;_.T.ih={};_.T.re={};_.T.ah=_.r;_.T.$g=[];_.T.$s=function(a){var c=_.t;try{if(a!=_.r)var h=window.parent.frames[a.id],c=h.iframer.id==a.id&&h.iframes.openedId_(_.kc.id)}catch(k){}try{_.T.ah={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.T.$g.length;++a)_.T.$g[a](_.T.ah);_.T.$g=[]}catch(m){}};_.T.gr=function(a){var c=a&&a.Uc,h=_.r;c&&(h={},h.id=c.da(),h.proxyChain=
a.zj);return h};(0,_.sc)();if(window.parent!=window){var a=_.R.la();a.gcv&&(0,_.zc)(a.gcv);var c=a.jsh;c&&(0,_.Bc)(c);(0,_.Dc)((0,_.Fc)(a,"..",""),_.kc);(0,_.Dc)(a,_.kc);(0,_.rc)()}_.T.ga=_.Wc;_.T.ra=_.Xc;_.T.Zt=_.$c;_.T.Zc=_.Yc;_.T.Vq=function(a){return _.T.ci[a]};_.T.Pj=function(a,c){_.T.ci[a]=c};_.T.Ct=_.Yc;_.T.ku=_.$c;_.T.Fg={};_.T.Fg.get=_.Wc;_.T.Fg.set=_.Xc;_.T.Vp=function(a,c){(0,_.pc)(a);_.T.re[a]=c||window[a]};_.T.gy=function(a){delete _.T.re[a]};_.T.open=function(a,c,h,k,m,q){3==arguments.length?
k={}:4==arguments.length&&"function"===typeof k&&(m=k,k={});var s="bubble"===c.style&&_.Zc&&_.Zc.va();return s?new _.Uc(a,c,h,k,s,m,q):(0,_.Gc)(c)?new _.Sc(a,c,h,k,m,q):new _.Qc(a,c,h,k,m,q)};_.T.close=function(a,c){_.kc&&_.kc._close&&_.kc._close(a,c)};_.T.$a=function(a,c,h){2==arguments.length&&"function"===typeof c&&(h=c,c={});var k=a||{};"height"in k||(k.height=_.bc.ef());k._methods=(0,_.Ec)(c||{},"..","",_.kc,_.p);_.kc&&_.kc._ready&&_.kc._ready(k,h)};_.T.pl=function(a){_.T.ah?a(_.T.ah):_.T.$g.push(a)};
_.T.Xs=function(a){return!!_.T.od[a]};_.T.Zq=function(){return["https://ssl.gstatic.com/gb/js/",(0,_.O)("googleapis.config/gcv")].join("")};_.T.mt=function(a){var c={mouseover:1,mouseout:1};if(_.kc._event)for(var h=0;h<a.length;h++){var k=a[h];k in c&&_.R.Te(window.document,k,function(a){_.kc._event({event:a.type,timestamp:(new window.Date).getTime()})},_.p)}};_.T.bu=_.Bc;_.T.Oj=_.Cc;_.T.Am=_.yc;_.T.pm=_.kc})();
(0,_.P)("iframes.allow",_.T.Vp);(0,_.P)("iframes.callSiblingOpener",_.T.gq);(0,_.P)("iframes.registerForOpenedSibling",_.T.ot);(0,_.P)("iframes.close",_.T.close);(0,_.P)("iframes.getGoogleConnectJsUri",_.T.Zq);(0,_.P)("iframes.getHandler",_.T.ga);(0,_.P)("iframes.getDeferredHandler",_.T.Vq);(0,_.P)("iframes.getParentInfo",_.T.pl);(0,_.P)("iframes.iframer",_.T.pm);(0,_.P)("iframes.open",_.T.open);(0,_.P)("iframes.openedId_",_.T.Xs);(0,_.P)("iframes.propagate",_.T.mt);(0,_.P)("iframes.ready",_.T.$a);
(0,_.P)("iframes.resize",_.T.Zc);(0,_.P)("iframes.setGoogleConnectJsVersion",_.T.Zt);(0,_.P)("iframes.setBootstrapHint",_.T.Oj);(0,_.P)("iframes.setJsHint",_.T.bu);(0,_.P)("iframes.setHandler",_.T.ra);(0,_.P)("iframes.setDeferredHandler",_.T.Pj);(0,_.P)("IframeBase",_.Kc);(0,_.P)("IframeBase.prototype.addCallback",_.Kc.prototype.na);(0,_.P)("IframeBase.prototype.getMethods",_.Kc.prototype.pg);(0,_.P)("IframeBase.prototype.getOpenerIframe",_.Kc.prototype.Ga);
(0,_.P)("IframeBase.prototype.getOpenParams",_.Kc.prototype.pa);(0,_.P)("IframeBase.prototype.getParams",_.Kc.prototype.wb);(0,_.P)("IframeBase.prototype.removeCallback",_.Kc.prototype.Xb);(0,_.P)("Iframe",_.Qc);(0,_.P)("Iframe.prototype.close",_.Qc.prototype.close);(0,_.P)("Iframe.prototype.exposeMethod",_.Qc.prototype.Ca);(0,_.P)("Iframe.prototype.getId",_.Qc.prototype.da);(0,_.P)("Iframe.prototype.getIframeEl",_.Qc.prototype.Z);(0,_.P)("Iframe.prototype.getSiteEl",_.Qc.prototype.V);
(0,_.P)("Iframe.prototype.openInto",_.Qc.prototype.Ra);(0,_.P)("Iframe.prototype.remove",_.Qc.prototype.remove);(0,_.P)("Iframe.prototype.setSiteEl",_.Qc.prototype.Hb);(0,_.P)("Iframe.prototype.addCallback",_.Qc.prototype.na);(0,_.P)("Iframe.prototype.getMethods",_.Qc.prototype.pg);(0,_.P)("Iframe.prototype.getOpenerIframe",_.Qc.prototype.Ga);(0,_.P)("Iframe.prototype.getOpenParams",_.Qc.prototype.pa);(0,_.P)("Iframe.prototype.getParams",_.Qc.prototype.wb);
(0,_.P)("Iframe.prototype.removeCallback",_.Qc.prototype.Xb);(0,_.P)("IframeProxy",_.Sc);(0,_.P)("IframeProxy.prototype.getTargetIframeId",_.Sc.prototype.i);(0,_.P)("IframeProxy.prototype.addCallback",_.Sc.prototype.na);(0,_.P)("IframeProxy.prototype.getMethods",_.Sc.prototype.pg);(0,_.P)("IframeProxy.prototype.getOpenerIframe",_.Sc.prototype.Ga);(0,_.P)("IframeProxy.prototype.getOpenParams",_.Sc.prototype.pa);(0,_.P)("IframeProxy.prototype.getParams",_.Sc.prototype.wb);
(0,_.P)("IframeProxy.prototype.removeCallback",_.Sc.prototype.Xb);(0,_.P)("IframeWindow",_.Uc);(0,_.P)("IframeWindow.prototype.close",_.Uc.prototype.close);(0,_.P)("IframeWindow.prototype.onClosed",_.Uc.prototype.b);(0,_.P)("iframes.util.getTopMostAccessibleWindow",_.T.O.vl);(0,_.P)("iframes.handlers.get",_.T.Fg.get);(0,_.P)("iframes.handlers.set",_.T.Fg.set);(0,_.P)("iframes.resizeMe",_.T.Ct);(0,_.P)("iframes.setVersionOverride",_.T.ku);
_.Kc.prototype.send=function(a,c,f){_.T.Dn(this,a,c,f)};_.kc.send=function(a,c,f){_.T.Dn(_.kc,a,c,f)};_.Kc.prototype.I=function(a,c){var f=this;f.na(a,function(a){c.call(f,a)})};_.T.Dn=function(a,c,f,g){var h=[];f&&h.push(f);g&&h.push(function(a){g.call(this,[a])});a[c]&&a[c].apply(a,h)};_.T.dd=(0,_.y)(_.p);(0,_.P)("iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.T.dd);(0,_.P)("IframeBase.prototype.send",_.Kc.prototype.send);(0,_.P)("IframeBase.prototype.register",_.Kc.prototype.I);
(0,_.P)("Iframe.prototype.send",_.Qc.prototype.send);(0,_.P)("Iframe.prototype.register",_.Qc.prototype.I);(0,_.P)("IframeProxy.prototype.send",_.Sc.prototype.send);(0,_.P)("IframeProxy.prototype.register",_.Sc.prototype.I);(0,_.P)("IframeWindow.prototype.send",_.Uc.prototype.send);(0,_.P)("IframeWindow.prototype.register",_.Uc.prototype.I);(0,_.P)("iframes.iframer.send",_.T.pm.send);

_.bd=function(a){var c=(0,_.Ca)();return c?c(a):_.t};_.cd=function(a){delete _.dd[a]};_.ed=function(a){if(a=_.dd[a])return a.state};_.fd=function(a,c){var f=_.dd[a];f&&f.state<c&&(f.state=c)};_.gd=function(a,c){var f=_.dd[a];f&&(f.args=c)};_.hd=function(a){if(a=_.dd[a])return a.oid};
_.dd=(0,_.va)(_.Aa,"rw",(0,_.N)());
_.id=function(a){if(a=(0,_.hd)(a)){var c=_.Ma.getElementById(a);c&&c.parentNode.removeChild(c);(0,_.cd)(a);(0,_.id)(a)}};_.jd=function(a){a=a.container;"string"===typeof a&&(a=window.document.getElementById(a));return a};_.kd=function(a){var c=a.clientWidth;return"position:absolute;top:-10000px;width:"+(c?c+"px":a.style.width||"300px")+";margin:0px;border-style:none;"};
_.ld=function(a,c){var f={},g=a.pa(),h=c&&c.width,k=c&&c.height;h||(h=g.width||a.width);k||(k=g.height||a.height);g.width=f.width=h;g.height=f.height=k;g=a.Z();h=a.da();(0,_.fd)(h,2);(0,_.gd)(h,f);a:{h=a.V();k=f||{};if((0,_.bd)()){if("number"===typeof(0,_.Ba)())break a;var m=g.id;if(m){f=(0,_.ed)(m);if(1===f||4===f)break a;(0,_.id)(m)}}if((f=h.nextSibling)&&f.getAttribute&&f.getAttribute("data-gapistub"))h.parentNode.removeChild(f),h.style.cssText="";var f=k.width,k=k.height,q=h.style;q.textIndent=
"0";q.margin="0";q.padding="0";q.background="transparent";q.borderStyle="none";q.cssFloat="none";q.styleFloat="none";q.lineHeight="normal";q.fontSize="1px";q.verticalAlign="baseline";h=h.style;h.display="inline-block";g=g.style;g.position="static";g.left=0;g.top=0;g.visibility="visible";f&&(h.width=g.width=f+"px");k&&(h.height=g.height=k+"px");m&&(0,_.fd)(m,3)}(m=c?c.title:_.r)&&a.Z().setAttribute("title",m)};_.md=function(a){var c=a.V();c&&c.removeChild(a.Z())};

_.nd={open:function(a){var c=(0,_.jd)(a.pa());return a.Ra(c,{style:(0,_.kd)(c,a)})},attach:function(a,c){var f=(0,_.jd)(a.pa()),g=c.id,h=c.getAttribute("data-postorigin")||c.src,k=/#(?:.*&)?rpctoken=(\d+)/.exec(h),k=k&&k[1];a.id=g;a.i=k;a.j=f;a.b=c;_.T.od[g]=a;k=(0,_.Dc)(a.Za);k._ready=a.Yg;k._close=a.close;k._open=a.Vm;k._resizeMe=a.uk;k._renderstart=a.Rm;(0,_.Ec)(k,g,"",a,_.p);_.S.kh(a.id,a.i);_.S.Ac(a.id,h);var f=_.T.$q({style:(0,_.kd)(f,a)}),m;for(m in f)window.Object.prototype.hasOwnProperty.call(f, m)&&("style"==m?a.b.style.cssText=f[m]:a.b.setAttribute(m,f[m]))}};_.nd.onready=_.ld;_.nd.onRenderStart=_.ld;_.nd.close=_.md;_.T.ra("inline",_.nd);


_.od=function(a){var c;a.match(/^https?%3A/i)&&(c=(0,window.decodeURIComponent)(a));a=c?c:a;return(0,_.ya)(window.document,a)};_.pd=function(a){a=a||"canonical";for(var c=window.document.getElementsByTagName("link"),f=0,g=c.length;f<g;f++){var h=c[f],k=h.getAttribute("rel");if(k&&k.toLowerCase()==a&&(h=h.getAttribute("href")))if((h=(0,_.od)(h))&&h.match(/^https?:\/\/[\w\-\_\.]+/i)!=_.r)return h}return window.location.href};_.qd=function(a,c,f,g){return(a="string"==typeof a?a:_.n)?(0,_.od)(a):(0,_.pd)(g)};
_.rd=function(a){return"string"==typeof a?""!=a&&"0"!=a&&"false"!=a.toLowerCase():!!a};_.sd=function(a){var c=(0,window.parseInt)(a,10);if(c==a)return(0,window.String)(c)};_.td=function(a){if((0,_.rd)(a))return"true"};_.ud=function(a){return"string"==typeof a&&_.vd[a.toLowerCase()]?a.toLowerCase():"standard"};_.wd=function(a,c){return"tall"==(0,_.ud)(c)?"true":a==_.r||(0,_.rd)(a)?"true":"false"};_.xd=function(a,c,f){a==_.r&&f&&(a=f.db,a==_.r&&(a=f.gwidget&&f.gwidget.db));return a||_.n};
_.yd=function(a,c,f){a==_.r&&f&&(a=f.ecp,a==_.r&&(a=f.gwidget&&f.gwidget.ecp));return a||_.n};_.vd={tall:{"true":{width:50,height:60},"false":{width:50,height:24}},small:{"false":{width:24,height:15},"true":{width:70,height:15}},medium:{"false":{width:32,height:20},"true":{width:90,height:20}},standard:{"false":{width:38,height:24},"true":{width:106,height:24}}};
_.zd={href:[_.qd,"url"],width:[_.sd],size:[_.ud],resize:[_.td],autosize:[_.td],count:[function(a,c){return(0,_.wd)(c.count,c.size)}],db:[_.xd],ecp:[_.yd],textcolor:[function(a){if("string"==typeof a&&a.match(/^[0-9A-F]{6}$/i))return a}],drm:[_.td],recommendations:[],fu:[],ad:[_.td],cr:[_.sd],ag:[_.sd],"fr-ai":[],"fr-sigh":[]};

_.Ad=(0,_.za)();
_.Bd=function(a,c,f){return(0,_.qd)(a,c,f,c.action?_.n:"publisher")};_.Cd=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};_.Dd=function(a){var c=_.n;"number"===typeof a?c=a:"string"===typeof a&&(c=(0,window.parseInt)(a,10));return c};_.Ed=function(a){(0,_.va)(_.Ad,a,0);return"___"+a+"_"+_.Ad[a]++};_.Fd=function(a,c){if("string"==typeof a){a=a.toLowerCase();var f;for(f=0;f<c.length;f++)if(c[f]==a)return a}};
_.Gd=function(a,c,f,g,h,k){var m;f.rd?m=c:(m=window.document.createElement("div"),c.setAttribute("data-gapistub",_.p),m.style.cssText="position:absolute;width:450px;left:-10000px;",c.parentNode.insertBefore(m,c));k.siteElement=m;m.id||(m.id=(0,_.Ed)(a));c=(0,_.N)();c[">type"]=a;(0,_.Va)(f,c);a=(0,_.Wb)(g,m,h);k.iframeNode=a;k.id=a.getAttribute("id")};_.Hd=function(a){return(0,_.Fd)(a,_.Id)};_.Jd=function(a){return(0,_.Fd)(a,_.Kd)};
_.Ld=function(a){a.source=[_.r,"source"];a.expandTo=[_.r,"expandTo"];a.align=[_.Jd];a.annotation=[_.Hd];a.origin=[_.Cd]};_.Md=function(a){var c=(0,_.va)(_.Aa,"sws",[]);return 0<=_.dc.call(c,a)};_.Nd=function(a,c){if("complete"!==_.Ma.readyState)try{a()}catch(f){}(0,_.nc)(c)};_.Od=function(a){if(_.wa.test(window.Object.keys))return window.Object.keys(a);var c=[],f;for(f in a)(0,_.Ua)(a,f)&&c.push(f);return c};
_.Pd=function(a,c){a:{_.Qd.ps0=(new window.Date).getTime();(0,_.Rd)("ps0");var f=("string"===typeof a?window.document.getElementById(a):a)||_.Ma,g;g=_.Ma.documentMode;if(f.querySelectorAll&&(!g||8<g)){g=c?[c]:(0,_.Od)(_.Sd).concat((0,_.Od)(_.Td)).concat((0,_.Od)(_.Ud));for(var h=[],k=0;k<g.length;k++){var m=g[k];h.push(".g-"+m,"g\\:"+m)}g=f.querySelectorAll(h.join(","))}else g=f.getElementsByTagName("*");f=(0,_.N)();for(h=0;h<g.length;h++){k=g[h];var q=k,m=c,s=q.nodeName.toLowerCase(),v=_.n;q.getAttribute("data-gapiscan")?
m=_.r:(0==s.indexOf("g:")?v=s.substr(2):(q=(q=(0,window.String)(q.className||q.getAttribute("class")))&&_.Vd.exec(q))&&(v=q[1]),m=v&&(_.Sd[v]||_.Td[v]||_.Ud[v])&&(!m||v===m)?v:_.r);m&&(k.setAttribute("data-gapiscan",_.p),(0,_.va)(f,m,[]).push(k))}for(var w in f)_.Wd.push(w);_.Qd.ps1=(new window.Date).getTime();(0,_.Rd)("ps1");if(w=_.Wd.join(":"))try{_.Oa.load(w,_.n)}catch(z){(0,_.ec)(z);break a}var D,k=[];for(D in f){h=f[D];g=0;for(w=h.length;g<w;g++){for(var q=h[g],m=D,s=v=q,q=(0,_.N)(),M=0!=s.nodeName.toLowerCase().indexOf("g:"),
I=0,G=s.attributes.length;I<G;I++){var J=s.attributes[I],V=J.name,pa=J.value;0<=_.dc.call(_.Xd,V)||(M&&0!=V.indexOf("data-")||"null"===pa||"specified"in J&&!J.specified)||(M&&(V=V.substr(5)),q[V.toLowerCase()]=pa)}s=s.style;(M=(0,_.Dd)(s&&s.height))&&(q.height=(0,window.String)(M));(s=(0,_.Dd)(s&&s.width))&&(q.width=(0,window.String)(s));(0,_.Yd)(m,v,q,k,w)}}}};
_.Zd=function(a,c){var f=(0,_.va)(_.Aa,"watt",(0,_.N)())[a];c&&f?(f(c),(f=c.iframeNode)&&f.setAttribute("data-gapiattached",_.p)):_.Oa.load(a,function(){var f=(0,_.va)(_.Aa,"watt",(0,_.N)())[a],h=c&&c.iframeNode;!h||!f?(0,_.Oa[a].go)(h&&h.parentNode):(f(c),h.setAttribute("data-gapiattached",_.p))})};
_.Yd=function(a,c,f,g,h){switch((0,_.$d)(c,a)){case 0:a=_.Ud[a]?a+"_annotation":a;g={};g.iframeNode=c;g.userParams=f;(0,_.Zd)(a,g);break;case 1:if(c.parentNode){var k=_.p;f.dontclear&&(k=_.t);delete f.dontclear;var m,q,s;q=s=a;"plus"==a&&f.action&&(s=a+"_"+f.action,q=a+"/"+f.action);(s=(0,_.O)("iframes/"+s+"/url"))||(s=":socialhost:/_/widget/render/"+q);q=(0,_.Ub)(s);s={};(0,_.Va)(f,s);s.hl=(0,_.O)("lang")||(0,_.O)("gwidget/lang")||"en-US";s.origin=(0,_.Cd)();s.exp=(0,_.O)("iframes/"+a+"/params/exp");
var v=(0,_.O)("iframes/"+a+"/params/location");if(v)for(var w=0;w<v.length;w++){var z=v[w];s[z]=_.Q.location[z]}switch(a){case "plus":case "follow":s.url=(0,_.Bd)(s.href,f,_.r);delete s.href;break;case "plusone":case "recobox":s.url=f.href?(0,_.od)(f.href):(0,_.pd)();s.db=(0,_.xd)(f.db,_.n,(0,_.O)());s.ecp=(0,_.yd)(f.ecp,_.n,(0,_.O)());delete s.href;break;case "signin":s.url=(0,_.pd)()}_.Aa.ILI&&(s.iloader="1");delete s["data-onload"];delete s.rd;s.gsrc=(0,_.O)("iframes/:source:");v=(0,_.O)("inline/css");
"undefined"!==typeof v&&(0<h&&v>=h)&&(s.ic="1");v=/^#|^fr-/;h={};for(var D in s)(0,_.Ua)(s,D)&&v.test(D)&&(h[D.replace(v,"")]=s[D],delete s[D]);D=[].concat(_.ae);v=(0,_.O)("iframes/"+a+"/methods");(0,_.cc)(v)&&(D=D.concat(v));for(m in f)if((0,_.Ua)(f,m)&&/^on/.test(m)&&("plus"!=a||"onconnect"!=m))D.push(m),delete s[m];delete s.callback;h._methods=D.join(",");m=(0,_.gb)(q,s,h);D={allowPost:1,attributes:_.be};D.dontclear=!k;k={};k.userParams=f;k.url=m;k.type=a;(0,_.Gd)(a,c,f,m,D,k);c=k.id;f=(0,_.N)();
f.id=c;f.userParams=k.userParams;f.url=k.url;f.type=k.type;f.state=1;_.dd[c]=f;c=k}else c=_.r;c&&((f=c.id)&&g.push(f),(0,_.Zd)(a,c))}};_.$d=function(a,c){if(a&&1===a.nodeType&&c)if(_.Ud[c]){if(_.ce[a.nodeName.toLowerCase()]){var f=a.innerHTML;return f&&f.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")?0:1}}else{if(_.Td[c])return 0;if(_.Sd[c])return 1}return _.r};_.de=function(a,c,f,g){_.ee[f]=_.ee[f]||!!g;(0,_.va)(_.fe,f,[]);_.fe[f].push([a,c])};
_.Rd=function(a,c,f){var g=_.ge.r;"function"===typeof g?g(a,c,f):g.push([a,c,f])};_.he=function(a,c,f,g){"_p"==c&&(0,_.l)((0,window.Error)("o`_p"));(0,_.ie)(a,c,f,g)};_.ie=function(a,c,f,g){(0,_.je)(c,f)[a]=g||(new window.Date).getTime();(0,_.Rd)(a,c,f)};_.je=function(a,c){var f=(0,_.va)(_.ke,a,(0,_.N)());return(0,_.va)(f,c,(0,_.N)())};_.le=function(a,c,f){var g=_.r;c&&f&&(g=(0,_.je)(c,f)[a]);return g||_.Qd[a]};_.me=function(a,c){(0,_.ie)("waaf0",a,c)};_.ne=function(a,c){(0,_.ie)("waaf1",a,c)};
_.oe=function(a,c){this.type=!a?"g":"_p"==a?"m":"w";this.name=a;this.b=c};_.pe=function(a){var c=[];c.push("l"+((0,_.O)("isPlusUser")?"1":"0"));var f="m"+(_.qe?"1":"0");c.push(f);if("m"==a.type)c.push("p"+a.b);else if("w"==a.type){var g="n"+a.b;c.push(g);"0"==a.b&&c.push(f+g)}c.push("u"+((0,_.O)("isLoggedIn")?"1":"0"));return c};
_.re=function(a,c,f){for(var g=new _.oe(c,f),h=(0,_.va)(_.se,g.key(),(0,_.N)()),k=_.fe[a]||[],m=0;m<k.length;++m){var q=k[m],s=h,v=q[0],w=a,z=c,D=f,q=(0,_.le)(q[1],z,D),w=(0,_.le)(w,z,D);s[v]=q&&w?w-q:_.r}_.ee[a]&&_.te&&((0,_.ue)(_.ve),(0,_.ue)(g))};_.we=function(a,c){c=c||[];for(var f=[],g=0;g<c.length;g++)f.push(a+c[g]);return f};
_.ue=function(a){var c=_.Q.__gapi_jstiming__;c.sn=_.xe[a.type];var f=new c.Timer(0),g;a:{switch(a.type){case "g":g="global";break a;case "m":g=a.b;break a;case "w":g=a.name;break a}g=_.n}f.name=g;g=_.t;var h=a.key(),k=_.se[h];f.tick("_start",_.r,0);for(var m in k)f.tick(m,"_start",k[m]),g=_.p;_.se[h]=(0,_.N)();if(g){m=[];g=(0,_.O)("lexps");m=m.concat((0,_.we)("e",g));m=m.concat((0,_.we)("",(0,_.pe)(a)));for(h=0;h<_.ye.length;h++)k=_.ye[h],0<=_.dc.call(g,k)&&(m=m.concat((0,_.we)(k?"e"+k:"",(0,_.pe)(a))));
m=(0,_.we)("abc_",m);c.report(f,{e:m.join(",")})}};_.ze=function(a){return a};_.Ae=function(a){var c=(0,_.O)(a);return"undefined"!==typeof c?c:(0,_.O)("gwidget/"+a)};_.Be=function(a){return function(c){var f=a;"number"===typeof c?f=c:"string"===typeof c&&(f=c.indexOf("px"),-1!=f&&(c=c.substring(0,f)),f=(0,window.parseInt)(c,10));return f}};_.Ce=function(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:_.r};_.De=function(){return(0,_.Ae)("lang")||"en-US"};
_.Ee=function(a){if(!_.T.ga("attach")){var c={},f=_.T.ga("inline"),g;for(g in f)f.hasOwnProperty(g)&&(c[g]=f[g]);c.open=function(a){var c=window.document.getElementById(a.pa().renderData.id);c||(0,_.l)((0,window.Error)("p"));return f.attach(a,c)};_.T.ra("attach",c)}a.style="attach"};
_.Fe=function(a){function c(a){for(var c={},f=0;f<a.length;++f)c[a[f].toLowerCase()]=1;c[g.Au]=1;g.Hs=c}function f(a){for(var c in a)if((0,_.Ua)(a,c)){g.xa[c]=[_.Ce];g.Wf.push(c);var f=a[c],q=_.r,s=_.r,v=_.r;"function"===typeof f?q=f:f&&"object"===typeof f&&(q=f.my,s=f.wh,v=f.ck);v&&(g.Wf.push(v),g.xa[v]=[_.Ce],g.jo[c]=v);q&&(g.xa[c]=[q]);s&&(g.vh[c]=s)}}var g={};g.dc=a[0];g.ek=-1;g.Sy="___"+g.dc+"_";g.Au="g:"+g.dc;g.ry="g-"+g.dc;g.pn=[];g.xa={};g.Wf=[];g.jo={};g.vh={};a[1]&&(g.Ys=a[1]);(function(a){g.xa=
a;for(var c in _.Ge)_.Ge.hasOwnProperty(c)&&!g.xa.hasOwnProperty(c)&&(g.xa[c]=_.Ge[c])})(a[2]||{});a[3]&&f(a[3]);a[4]&&c(a[4]);a[5]&&(g.jh=a[5]);g.Ly=a[6]===_.p;g.kt=a[7];g.Hs||c(_.He);g.xj=function(a){g.ek++;(0,_.he)("wrs",g.dc,(0,window.String)(g.ek));var c=[],f=a.element,q=a.xa,s=":"+g.dc;":plus"==s&&(a.Ge&&a.Ge.action)&&(s+="_"+a.Ge.action);var v=(0,_.Je)(g,q),w={},z;for(z in a.Ge)a.Ge[z]!=_.r&&(w[z]=a.Ge[z]);z={container:f.id,renderData:a.xt,style:"inline",height:q.height,width:q.width};(0,_.Ee)(z);
g.jh&&(c[2]=z,c[3]=w,c[4]=v,g.jh("i",c));s=_.T.open(s,z,w,v);a=a.vq;(0,_.Ke)(s,q);(0,_.Le)(s,f);(0,_.Me)(g,s,a);c[5]=s;g.jh&&g.jh("e",c)};return g};_.Je=function(a,c){for(var f={},g=a.Wf.length-1;0<=g;--g){var h=a.Wf[g],k=c[a.jo[h]||h]||c[h],m=c[h];m&&k!==m&&(k=function(a,c){return function(f){c.apply(this,arguments);a.apply(this,arguments)}}(k,m));k&&(f[h]=k)}for(var q in a.vh)a.vh.hasOwnProperty(q)&&(f[q]=(0,_.Ne)(f[q]||(0,_.u)(),a.vh[q]));return f};
_.Ne=function(a,c){return function(f){var g=c(f);if(g){var h=f.href||_.r;if(_.Oe&&window._gat)try{var k=window._gat._getTrackerByName("~0");k&&"UA-XXXXX-X"!=k._getAccount()?k._trackSocial("Google",g,h):window._gaq&&window._gaq.push(["_trackSocial","Google",g,h])}catch(m){}if(_.Pe&&window.dataLayer)try{window.dataLayer.push({event:"social",socialjsuixNetwork:"Google",socialAction:g,socialTarget:h})}catch(q){}}a.call(this,f)}};
_.Ke=function(a,c){if(c.onready){var f=_.t,g=function(){f||(f=_.p,c.onready.call(_.r))};a.I("ready",g,_.T.dd);a.I("renderstart",g,_.T.dd)}(0,_.Qe)(a)};
_.Me=function(a,c,f){function g(){s||(s=_.p,h(),f&&(0,_.he)("wrrt",k,m),(0,_.he)("wrri",k,m))}function h(){q||(q=_.p,f&&(0,_.he)("wrdt",k,m),(0,_.he)("wrdi",k,m))}var k=a.dc,m=(0,window.String)(a.ek),q=_.t;c.I("renderstart",h,_.T.dd);var s=_.t;c.I("ready",g,_.T.dd);_.S.I("widget-interactive-"+c.id,g);_.S.I("widget-csi-tick-"+c.id,function(a,c,f){"wdc"===a||"wci"===a?(0,_.he)("wdc",k,m,f):"wje0"===a||"wji_"===a?(0,_.he)("wje0",k,m,f):"wje1"===a||"wji"===a?(0,_.he)("wje1",k,m,f):"wh0"==a?(0,_.ie)("wh0",
k,m,f):"wh1"==a&&(0,_.ie)("wh1",k,m,f)})};_.Le=function(a,c){function f(f){f=f||a;var h=(0,_.Pc)(a,f.width);h&&c.style.width!=h.Ed&&(c.style.width=h.Ed);if((f=(0,_.Pc)(a,f.height))&&c.style.height!=f.Ed)c.style.height=f.Ed}a.I("ready",f,_.T.dd);a.I("renderstart",f,_.T.dd);a.I("resize",f,_.T.dd)};_.Re=function(a,c){for(var f in _.Ge)if(_.Ge.hasOwnProperty(f)){var g=_.Ge[f][1];g&&!c.hasOwnProperty(g)&&(c[g]=a[g])}return c};
_.Se=function(a,c){var f={},g;for(g in a)a.hasOwnProperty(g)&&(f[a[g][1]||g]=(a[g]&&a[g][0]||_.ze)(c[g.toLowerCase()],c,_.Te));return f};_.Ue=function(a){if(a=a.kt)for(var c=0;c<a.length;c++)(new window.Image).src=a[c]};
_.Ve=function(a){function c(){"onload"===_.We&&g.go()}var f=(0,_.Fe)(a);(0,_.Ue)(f);(0,_.tc)(f.dc,function(a){var c=a.userParams,g=a.siteElement;g||(g=(g=a.iframeNode)&&g.parentNode);if(g&&1===g.nodeType){var q=(0,_.Se)(f.xa,c);f.pn.push({element:g,xa:q,Ge:(0,_.Re)(q,(0,_.Se)(f.Ys,c)),By:3,vq:!!c["data-onload"],xt:a})}a=f.pn;for(c=f.xj;0<a.length;)c(a.shift())});_.Sd[f.dc]=_.p;var g={J:function(a,c){var g=c||{};g.type=f.dc;var q=g.type;delete g.type;var s=("string"===typeof a?window.document.getElementById(a):
a)||_.n;if(s){var v={},w;for(w in g)(0,_.Ua)(g,w)&&(v[w.toLowerCase()]=g[w]);v.rd=1;(0,_.Yd)(q,s,v,[],0)}else(0,_.ec)("string"==="gapi."+q+".render: missing element "+typeof a?a:"")},go:function(a){(0,_.Pd)(a,f.dc)},b:function(){var a=(0,_.za)(),c;for(c in a)delete a[c]}};(0,_.Md)(f.dc)||(0,_.Nd)(c,c);return g};_.Qe=function(){};_.ae="onPlusOne _ready _close,_open _resizeMe _renderstart oncircled".split(" ");_.Id="inline bubble none only pp vertical-bubble".split(" ");_.Kd=["left","right"];
_.Xd=["style","data-gapiscan"];_.be={style:"position:absolute;top:-10000px;width:450px;margin:0px;borderStyle:none"};_.ce={button:_.p,div:_.p,span:_.p};_.Vd=/(?:^|\s)g-((\S)*)(?:$|\s)/;_.Sd=(0,_.va)(_.Aa,"SW",(0,_.N)());_.Td=(0,_.va)(_.Aa,"SA",(0,_.N)());_.Ud=(0,_.va)(_.Aa,"SM",(0,_.N)());_.Wd=(0,_.va)(_.Aa,"FW",[]);
(0,_.va)(_.Oa,"platform",{}).go=_.Pd;_.ge=(0,_.va)(_.Aa,"perf",(0,_.N)());_.Qd=(0,_.va)(_.ge,"g",(0,_.N)());_.ke=(0,_.va)(_.ge,"i",(0,_.N)());(0,_.va)(_.ge,"r",[]);_.ee=(0,_.N)();_.fe=(0,_.N)();(function(){function a(a){this.t={};this.tick=function(a,c,f){this.t[a]=[f!=_.n?f:(new window.Date).getTime(),c]};this.tick("start",_.r,a)}var c=new a;window.__gapi_jstiming__={Timer:a,load:c};if(window.performance&&window.performance.timing){var c=window.performance.timing,f=window.__gapi_jstiming__.load,g=c.navigationStart,c=c.responseStart;0<g&&c>=g&&(f.tick("_wtsrt",_.n,g),f.tick("wtsrt_","_wtsrt",c),f.tick("tbsd_","wtsrt_"))}try{c=_.r,window.chrome&&window.chrome.csi&&(c=window.Math.floor(window.chrome.csi().pageT),
f&&0<g&&(f.tick("_tbnd",_.n,window.chrome.csi().startE),f.tick("tbnd_","_tbnd",g))),c==_.r&&window.gtbExternal&&(c=window.gtbExternal.pageT()),c==_.r&&window.external&&(c=window.external.pageT,f&&0<g&&(f.tick("_tbnd",_.n,window.external.startE),f.tick("tbnd_","_tbnd",g))),c&&(window.__gapi_jstiming__.pt=c)}catch(h){}})();
if(window.__gapi_jstiming__){window.__gapi_jstiming__.Ok={};window.__gapi_jstiming__.yt=1;_.Xe=function(a,c,f){var g=a.t[c],h=a.t.start;if(g&&(h||f))return g=a.t[c][0],f!=_.n?h=f:h=h[0],g-h};window.__gapi_jstiming__.getTick=_.Xe;window.__gapi_jstiming__.getLabels=function(a){var c=[],f;for(f in a.t)c.push(f);return c};_.Ye=function(a,c,f){var g="";window.__gapi_jstiming__.pt&&(g+="&srt="+window.__gapi_jstiming__.pt);try{window.external&&window.external.tran?g+="&tran="+window.external.tran:window.gtbExternal&&
window.gtbExternal.tran?g+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(g+="&tran="+window.chrome.csi().tran)}catch(h){}var k=window.chrome;if(k&&(k=k.loadTimes)){k().wasFetchedViaSpdy&&(g+="&p=s");if(k().wasNpnNegotiated){var g=g+"&npn=1",m=k().npnNegotiatedProtocol;m&&(g+="&npnv="+(window.encodeURIComponent||window.escape)(m))}k().wasAlternateProtocolAvailable&&(g+="&apa=1")}var q=a.t,s=q.start,k=[],m=[],v;for(v in q)if("start"!=v&&0!=v.indexOf("_")){var w=q[v][1];w?q[w]&&
m.push(v+"."+(0,_.Xe)(a,v,q[w][0])):s&&k.push(v+"."+(0,_.Xe)(a,v))}if(c)for(var z in c)g+="&"+z+"="+c[z];(c=f)||(c="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");return[c,"?v=3","&s="+(window.__gapi_jstiming__.sn||"gwidget")+"&action=",a.name,m.length?"&it="+m.join(","):"","",g,"&rt=",k.join(",")].join("")};_.Ze=function(a,c,f){a=(0,_.Ye)(a,c,f);if(!a)return"";c=new window.Image;var g=window.__gapi_jstiming__.yt++;window.__gapi_jstiming__.Ok[g]=
c;c.onload=c.onerror=function(){window.__gapi_jstiming__&&delete window.__gapi_jstiming__.Ok[g]};c.src=a;c=_.r;return a};window.__gapi_jstiming__.report=function(a,c,f){if("prerender"==window.document.webkitVisibilityState){var g=_.t,h=function(){if(!g){c?c.prerender="1":c={prerender:"1"};var k;"prerender"==window.document.webkitVisibilityState?k=_.t:((0,_.Ze)(a,c,f),k=_.p);k&&(g=_.p,window.document.removeEventListener("webkitvisibilitychange",h,_.t))}};window.document.addEventListener("webkitvisibilitychange", h,_.t);return""}return(0,_.Ze)(a,c,f)}};
_.ye=[73,74,77,78];_.xe={g:"gapi_global",m:"gapi_module",w:"gwidget"};_.oe.prototype.key=function(){switch(this.type){case "g":return this.type;case "m":return this.type+"."+this.b;case "w":return this.type+"."+this.name+this.b}};_.ve=new _.oe;_.qe=window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/);_.se=(0,_.va)(_.ge,"_c",(0,_.N)());_.te=window.Math.random()<((0,_.O)("csi/rate")||0);(0,_.de)("blt","bs0","bs1");(0,_.de)("psi","ps0","ps1");(0,_.de)("rpcqi","rqe","rqd");
(0,_.de)("mli","ml0","ml1");(0,_.de)("mei","me0","me1",_.p);(0,_.de)("wci","wrs","wdc");(0,_.de)("wdi","wrs","wrdi");(0,_.de)("wdt","bs0","wrdt");(0,_.de)("wri","wrs","wrri",_.p);(0,_.de)("wrt","bs0","wrrt");(0,_.de)("wji","wje0","wje1",_.p);(0,_.de)("wjli","wjl0","wjl1");(0,_.de)("whi","wh0","wh1",_.p);(0,_.de)("wai","waaf0","waaf1",_.p);(0,_.de)("wadi","wrs","waaf1",_.p);(0,_.de)("wadt","bs0","waaf1",_.p);_.$e=_.ge.r; if("function"!==typeof _.$e){for(_.af;_.af=_.$e.shift();)_.re.apply(_.r,_.af);_.ge.r=_.re};
_.He=["div"];_.We="onload";_.Oe=_.p;_.Pe=_.p;_.Te=_.r;_.Te=(0,_.O)();(0,_.O)("gwidget");_.bf=(0,_.Ae)("parsetags");_.We="explicit"===_.bf||"onload"===_.bf?_.bf:_.We;_.cf=(0,_.Ae)("google_analytics");"undefined"!==typeof _.cf&&(_.Oe=!!_.cf);_.df=(0,_.Ae)("data_layer");"undefined"!==typeof _.df&&(_.Pe=!!_.df);_.Ge=function(){var a={};a.width=[(0,_.Be)(450)];a.height=[(0,_.Be)(24)];a.onready=[_.Ce];a.lang=[_.De,"hl"];a.iloader=[function(){return _.Aa.ILI},"iloader"];return a}();

_.Wu=(window.gapi||{}).load;
_.T.Pj("bubble",function(a){(0,_.Wu)("iframes-styles-bubble",a)});
_.T.Pj("slide-menu",function(a){(0,_.Wu)("iframes-styles-slide-menu",a)});

_.Nx=function(a,c,f){a=(0,_.Hd)(a);c=(0,_.ud)(c);if(""!=a){if("inline"==a||"only"==a)return a=450,f.width&&(a=120<f.width?f.width:120),{width:a,height:_.vd[c]["false"].height};if("bubble"!=a){if("none"==a)return _.vd[c]["false"];if("pp"==a)return _.Ox}}return _.vd[c]["true"]};_.Ox={width:180,height:35};
_.Ya=_.Za=function(){var a={0:"plusone"},c=(0,_.O)("iframes/plusone/preloadUrl");c&&(a[7]=c);(0,_.Ld)(_.zd);a[1]=_.zd;a[2]={width:[function(a,c){return c.annotation?(0,_.Nx)(c.annotation,c.size,c).width:_.vd[(0,_.ud)(c.size)][(0,_.wd)(c.count,c.size)].width}],height:[function(a,c){return c.annotation?(0,_.Nx)(c.annotation,c.size,c).height:_.vd[(0,_.ud)(c.size)][(0,_.wd)(c.count,c.size)].height}]};a[3]={onPlusOne:{wh:function(a){return"on"==a.state?"+1":_.r},ck:"callback"},onstartinteraction:_.p,onendinteraction:_.p, onpopup:_.p};a[4]=["div","button"];return(0,_.Ve)(a)}();
(0,_.P)("gapi.plusone.render",_.Za.J);(0,_.P)("gapi.plusone.go",_.Za.go);(0,_.P)("googleapisv0.plusone.render",_.Ya.J);(0,_.P)("googleapisv0.plusone.go",_.Ya.go);
});

// Copyright 2002-2013 Google Inc.
